-- 1. Ensure City Exists (Diadema)
INSERT INTO public.cities (name, slug, state)
VALUES ('Diadema', 'diadema', 'SP')
ON CONFLICT (slug) DO NOTHING;

-- 2. Insert Providers
-- Using gen_random_uuid() for IDs
-- Cleanup website URLs (removing markdown)
-- Appending -diadema to slugs to avoid conflicts
INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  (gen_random_uuid(), 'Imobiliária Góes', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Avenida Antônio Piranga, 662', '11947234455', '1140511122', 'contato@imobiliariagoes.com.br', 'manual_google', true, 'imobiliaria-goes-diadema', 'imobiliaria', 'https://www.imobiliariagoes.com.br', '18451J'),
  (gen_random_uuid(), 'Imobiliária Diadema', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Rua Graciosa, 517', '11985552020', '1140512000', 'vendas@imobiliariadiadema.com.br', 'manual_google', true, 'imobiliaria-diadema', 'imobiliaria', 'https://www.imobiliariadiadema.com.br', '12345J'),
  (gen_random_uuid(), 'Mazuche Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Taboão', 'Avenida Dom João VI, 508', '11974011500', '1140917700', null, 'manual_google', true, 'mazuche-imoveis-diadema', 'imobiliaria', 'https://www.mazuche.com.br', '20155J'),
  (gen_random_uuid(), 'Gatti Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Avenida Alda, 439', '11999887766', '1140562233', 'contato@gattiimoveis.com.br', 'manual_google', true, 'gatti-imoveis-diadema', 'imobiliaria', 'https://www.gattiimoveis.com.br', '19877J'),
  (gen_random_uuid(), 'Fênix Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Rua General Manoel de Mesquita, 10', '11940121314', '1140513030', 'fenix@feniximoveis.com.br', 'manual_google', true, 'fenix-imoveis-diadema', 'imobiliaria', 'https://www.feniximoveis.com.br', '15644J'),
  (gen_random_uuid(), 'S. Santos Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Canhema', 'Avenida Assembleia, 574', '11947223344', '1140571000', null, 'manual_google', true, 's-santos-imoveis-diadema', 'imobiliaria', 'https://www.ssantosimoveis.com.br', '22334J'),
  (gen_random_uuid(), 'Teto Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Rua Orense, 41', '11947008899', '1140561515', 'atendimento@tetoimoveis.com.br', 'manual_google', true, 'teto-imoveis-diadema', 'imobiliaria', 'https://www.tetoimoveis.com.br', '12988J'),
  (gen_random_uuid(), 'Plazza Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Avenida Alda, 218', '11999112233', '1140563434', null, 'manual_google', true, 'plazza-imoveis-diadema', 'imobiliaria', 'https://www.plazzaimoveis.com.br', '17555J'),
  (gen_random_uuid(), 'Adonai Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Serraria', 'Rua Botocudos, 310', '11963221100', '1140431010', 'contato@adonaiimoveis.com.br', 'manual_google', true, 'adonai-imoveis-diadema', 'imobiliaria', 'https://www.adonaiimoveis.com.br', '25441J'),
  (gen_random_uuid(), 'Habitar Imóveis Diadema', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Avenida São José, 452', '11940332211', '1140511515', null, 'manual_google', true, 'habitar-imoveis-diadema', 'imobiliaria', 'https://www.habitarimoveis.com.br', '19222J'),
  (gen_random_uuid(), 'Nova Diadema Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Rua Manoel da Nóbrega, 480', '11947885566', '1140552020', 'vendas@novadiadema.com.br', 'manual_google', true, 'nova-diadema-imoveis', 'imobiliaria', 'https://www.novadiadema.com.br', '28444J'),
  (gen_random_uuid(), 'Elite Imóveis Diadema', (SELECT id FROM public.cities WHERE slug='diadema'), 'Piraporinha', 'Avenida Piraporinha, 1120', '11956001122', '1140663344', null, 'manual_google', true, 'elite-imoveis-diadema', 'imobiliaria', 'https://www.eliteimoveis.com.br', '21777J'),
  (gen_random_uuid(), 'Casari Imóveis Diadema', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Rua João de Almeida, 65', '11974443322', '1140534455', 'diadema@casari.com.br', 'manual_google', true, 'casari-imoveis-diadema', 'imobiliaria', 'https://www.casari.com.br', '00900J'),
  (gen_random_uuid(), 'Viana Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Conceição', 'Avenida Dom Pedro I, 880', '11988776655', '1140567788', null, 'manual_google', true, 'viana-imoveis-diadema', 'imobiliaria', 'https://www.vianaimoveis.com.br', '24555J'),
  (gen_random_uuid(), 'Coliseu Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Avenida Fabio Eduardo Ramos Esquivel, 120', '11947558899', '1140445566', 'contato@coliseuimoveis.com.br', 'manual_google', true, 'coliseu-imoveis-diadema', 'imobiliaria', 'https://www.coliseuimoveis.com.br', '26111J'),
  (gen_random_uuid(), 'Meta Imóveis Diadema', (SELECT id FROM public.cities WHERE slug='diadema'), 'Eldorado', 'Avenida Nossa Senhora dos Navegantes, 450', '11963004455', '1140472233', null, 'manual_google', true, 'meta-imoveis-diadema', 'imobiliaria', 'https://www.metaimoveis.com.br', '18999J'),
  (gen_random_uuid(), 'Opção Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Taboão', 'Rua Áustria, 45', '11940112233', '1140915000', null, 'manual_google', true, 'opcao-imoveis-diadema', 'imobiliaria', 'https://www.opcaoimoveis.com.br', '14222J'),
  (gen_random_uuid(), 'Conquista Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Rua Ipiranga, 210', '11947112233', '1140568800', null, 'manual_google', true, 'conquista-imoveis-diadema', 'imobiliaria', 'https://www.conquistadiadema.com.br', '22555J'),
  (gen_random_uuid(), 'J. Gual Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Avenida Alda, 630', '11999778899', '1140511010', 'contato@jgual.com.br', 'manual_google', true, 'j-gual-imoveis-diadema', 'imobiliaria', 'https://www.jgual.com.br', '16333J'),
  (gen_random_uuid(), 'Real Imóveis Diadema', (SELECT id FROM public.cities WHERE slug='diadema'), 'Campanário', 'Avenida Paranapanema, 1020', '11988112233', '1140483322', null, 'manual_google', true, 'real-imoveis-diadema', 'imobiliaria', 'https://www.realimoveisdiadema.com.br', '15222J'),
  (gen_random_uuid(), 'Padrão Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Avenida São José, 110', '11940115544', '1140553311', null, 'manual_google', true, 'padrao-imoveis-diadema', 'imobiliaria', 'https://www.padraoimoveis.com.br', '19444J'),
  (gen_random_uuid(), 'Estilo Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Serraria', 'Avenida Lico Maia, 450', '11963228877', '1140432020', null, 'manual_google', true, 'estilo-imoveis-diadema', 'imobiliaria', 'https://www.estiloimoveis.com.br', '23111J'),
  (gen_random_uuid(), 'Líder Imóveis Diadema', (SELECT id FROM public.cities WHERE slug='diadema'), 'Inamar', 'Avenida Maria Leonor, 85', '11947113322', '1140415566', null, 'manual_google', true, 'lider-imoveis-diadema', 'imobiliaria', 'https://www.liderdiadema.com.br', '17888J'),
  (gen_random_uuid(), 'Aliança Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Rua Orense, 350', '11947449900', '1140562010', null, 'manual_google', true, 'alianca-imoveis-diadema', 'imobiliaria', 'https://www.aliancadiadema.com.br', '20555J'),
  (gen_random_uuid(), 'Progresso Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Avenida Alda, 810', '11940001122', '1140511234', null, 'manual_google', true, 'progresso-imoveis-diadema', 'imobiliaria', 'https://www.progressoimoveis.com.br', '22444J'),
  (gen_random_uuid(), 'Futura Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Taboão', 'Avenida Paranapanema, 150', '11999118877', '1140914433', null, 'manual_google', true, 'futura-imoveis-diadema', 'imobiliaria', 'https://www.futuradiadema.com.br', '24111J'),
  (gen_random_uuid(), 'Continental Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Rua Manoel da Nóbrega, 710', '11947225566', '1140551010', null, 'manual_google', true, 'continental-imoveis-diadema', 'imobiliaria', 'https://www.continentalimoveis.com.br', '18222J'),
  (gen_random_uuid(), 'Brasil Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Serraria', 'Rua José Bonifácio, 320', '11963114455', '1140441122', null, 'manual_google', true, 'brasil-imoveis-diadema', 'imobiliaria', 'https://www.brasilimoveisdiadema.com.br', '21333J'),
  (gen_random_uuid(), 'Prime Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Avenida Antônio Piranga, 850', '11947003322', '1140514455', null, 'manual_google', true, 'prime-imoveis-diadema', 'imobiliaria', 'https://www.primediadema.com.br', '26444J'),
  (gen_random_uuid(), 'Global Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Eldorado', 'Estrada do Alvarenga, 1200', '11988221144', '1140475588', null, 'manual_google', true, 'global-imoveis-diadema', 'imobiliaria', 'https://www.globaldiadema.com.br', '19555J'),
  (gen_random_uuid(), 'Fokus Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Rua Graciosa, 110', '11940117788', '1140562211', null, 'manual_google', true, 'fokus-imoveis-diadema', 'imobiliaria', 'https://www.fokusimoveis.com.br', '23666J'),
  (gen_random_uuid(), 'Ponto Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Inamar', 'Avenida Inamar, 450', '11947228899', '1140412233', null, 'manual_google', true, 'ponto-imoveis-diadema', 'imobiliaria', 'https://www.pontoimoveisdiadema.com.br', '16777J'),
  (gen_random_uuid(), 'Rumo Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Piraporinha', 'Rua das Perobas, 120', '11999114422', '1140661133', null, 'manual_google', true, 'rumo-imoveis-diadema', 'imobiliaria', 'https://www.rumodiadema.com.br', '21888J'),
  (gen_random_uuid(), 'Ativa Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Rua Amélia Eugênia, 150', '11940336677', '1140512244', null, 'manual_google', true, 'ativa-imoveis-diadema', 'imobiliaria', 'https://www.ativadiadema.com.br', '19666J'),
  (gen_random_uuid(), 'Morar Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Serraria', 'Avenida Rotary, 800', '11963220011', '1140431100', null, 'manual_google', true, 'morar-imoveis-diadema', 'imobiliaria', 'https://www.morardiadema.com.br', '24888J'),
  (gen_random_uuid(), 'Alpha Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Rua Orense, 520', '11947551100', '1140563322', null, 'manual_google', true, 'alpha-imoveis-diadema', 'imobiliaria', 'https://www.alphadiadema.com.br', '17333J'),
  (gen_random_uuid(), 'Omega Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Taboão', 'Avenida das Nações, 410', '11999117766', '1140912233', null, 'manual_google', true, 'omega-imoveis-diadema', 'imobiliaria', 'https://www.omegadiadema.com.br', '22666J'),
  (gen_random_uuid(), 'Delta Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Rua Ipiranga, 55', '11947220011', '1140552233', null, 'manual_google', true, 'delta-imoveis-diadema', 'imobiliaria', 'https://www.deltadiadema.com.br', '18444J'),
  (gen_random_uuid(), 'Viver Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Piraporinha', 'Avenida Piraporinha, 1500', '11956004433', '1140662244', null, 'manual_google', true, 'viver-imoveis-diadema', 'imobiliaria', 'https://www.viverdiadema.com.br', '25111J'),
  (gen_random_uuid(), 'Sonho Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Avenida Alda, 1020', '11940114455', '1140515566', null, 'manual_google', true, 'sonho-imoveis-diadema', 'imobiliaria', 'https://www.sonhodiadema.com.br', '20777J'),
  (gen_random_uuid(), 'Master Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Serraria', 'Rua dos Pinheiros, 310', '11963224455', '1140435566', null, 'manual_google', true, 'master-imoveis-diadema', 'imobiliaria', 'https://www.masterdiadema.com.br', '15444J'),
  (gen_random_uuid(), 'Premium Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Avenida São José, 820', '11947115566', '1140554433', null, 'manual_google', true, 'premium-imoveis-diadema', 'imobiliaria', 'https://www.premiumdiadema.com.br', '21444J'),
  (gen_random_uuid(), 'Exclusive Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Conceição', 'Rua de Conceição, 45', '11988114455', '1140561122', null, 'manual_google', true, 'exclusive-imoveis-diadema', 'imobiliaria', 'https://www.exclusivediadema.com.br', '24333J'),
  (gen_random_uuid(), 'Nobre Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Avenida Antônio Piranga, 1100', '11947005544', '1140516677', null, 'manual_google', true, 'nobre-imoveis-diadema', 'imobiliaria', 'https://www.nobrediadema.com.br', '19333J'),
  (gen_random_uuid(), 'Atitude Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Eldorado', 'Rua das Flores, 12', '11988225566', '1140471144', null, 'manual_google', true, 'atitude-imoveis-diadema', 'imobiliaria', 'https://www.atitudediadema.com.br', '22111J'),
  (gen_random_uuid(), 'Valor Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Rua Manoel da Nóbrega, 1100', '11940118899', '1140557788', null, 'manual_google', true, 'valor-imoveis-diadema', 'imobiliaria', 'https://www.valordiadema.com.br', '16444J'),
  (gen_random_uuid(), 'Credibilidade Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Piraporinha', 'Avenida Piraporinha, 2100', '11956008899', '1140667788', null, 'manual_google', true, 'credibilidade-imoveis-diadema', 'imobiliaria', 'https://www.credibilidadediadema.com.br', '23444J'),
  (gen_random_uuid(), 'União Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Avenida Alda, 1500', '11947221100', '1140513344', null, 'manual_google', true, 'uniao-imoveis-diadema', 'imobiliaria', 'https://www.uniaodiadema.com.br', '20111J'),
  (gen_random_uuid(), 'Vitória Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Serraria', 'Avenida Rotary, 1200', '11963223322', '1140436677', null, 'manual_google', true, 'vitoria-imoveis-diadema', 'imobiliaria', 'https://www.vitoriadiadema.com.br', '15888J'),
  (gen_random_uuid(), 'Horizonte Imóveis', (SELECT id FROM public.cities WHERE slug='diadema'), 'Centro', 'Rua Orense, 850', '11947441122', '1140564455', null, 'manual_google', true, 'horizonte-imoveis-diadema', 'imobiliaria', 'https://www.horizontediadema.com.br', '21999J'),
  (gen_random_uuid(), 'Imobiliária Vila Real', (SELECT id FROM public.cities WHERE slug='diadema'), 'Taboão', 'Avenida Prestes Maia, 450', '11999113344', '1140915566', null, 'manual_google', true, 'imobiliaria-vila-real-diadema', 'imobiliaria', 'https://www.vilarealdiadema.com.br', '14555J')
ON CONFLICT (slug) DO NOTHING;
