-- 1. Ensure City Exists (Mauá)
INSERT INTO public.cities (name, slug, state)
VALUES ('Mauá', 'maua', 'SP')
ON CONFLICT (slug) DO NOTHING;

-- 2. Insert Providers
-- Using gen_random_uuid() for IDs
-- Cleanup website URLs (removing markdown)
-- Ensuring slugs have -maua suffix where appropriate for uniqueness
INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  (gen_random_uuid(), 'Gouveia Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua General Osório, 187', '11947230001', '1145123000', 'contato@gouveiaimoveis.com.br', 'manual_google', true, 'gouveia-imoveis-maua', 'imobiliaria', 'https://www.gouveiaimoveis.com.br', '14785J'),
  (gen_random_uuid(), 'Atos Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Jardim Pedroso', 'Avenida Dom José Gaspar, 605', '11951125250', '1145112525', 'atos@atosimoveis.com.br', 'manual_google', true, 'atos-imoveis-maua', 'imobiliaria', 'https://www.atosimoveis.com.br', '26034J'),
  (gen_random_uuid(), 'Carisma Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Parque São Vicente', 'Avenida João Ramalho, 1880', '11947251000', '1145551000', 'vendas@carismaimoveis.com.br', 'manual_google', true, 'carisma-imoveis-maua', 'imobiliaria', 'https://www.carismaimoveis.com.br', '24700J'),
  (gen_random_uuid(), 'Vila Rica Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Rui Barbosa, 68', '11947147444', '1145147444', 'vilarica@vilaricaimoveis.com.br', 'manual_google', true, 'vila-rica-imoveis-maua', 'imobiliaria', 'https://www.vilarica.com.br', '20110J'),
  (gen_random_uuid(), 'Mauá Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Luis Mariani, 182', '11945143000', '1145143000', 'atendimento@mauaimoveis.com.br', 'manual_google', true, 'maua-imoveis', 'imobiliaria', 'https://www.mauaimoveis.com.br', '19400J'),
  (gen_random_uuid(), 'Mendes Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Noêmia', 'Rua Brás Cubas, 451', '11947126000', '1145126000', 'mendes@mendesimoveis.com.br', 'manual_google', true, 'mendes-imoveis-maua', 'imobiliaria', 'https://www.mendesimoveis.com.br', '22850J'),
  (gen_random_uuid(), 'Adonai Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Manoel Pedro de Oliveira, 238', '11945415050', '1145415050', null, 'manual_google', true, 'adonai-imoveis-maua', 'imobiliaria', 'https://www.adonaiimoveismaua.com.br', '28140J'),
  (gen_random_uuid(), 'Excellence Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Jardim Mauá', 'Avenida Itapark, 2030', '11947124040', '1145124040', 'excellence@excellenceimoveis.com.br', 'manual_google', true, 'excellence-imoveis-maua', 'imobiliaria', 'http://www.excellenceimoveis.com.br', '30155J'),
  (gen_random_uuid(), 'Plena Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Assis', 'Avenida Assis Brasil, 520', '11945451999', '1145451999', 'contato@plenaimoveis.com.br', 'manual_google', true, 'plena-imoveis-maua', 'imobiliaria', 'https://www.plenaimoveis.com.br', '18990J'),
  (gen_random_uuid(), 'Moratta Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Brás Cubas, 350', '11945142020', '1145142020', 'atendimento@morattaimoveis.com.br', 'manual_google', true, 'moratta-imoveis-maua', 'imobiliaria', 'https://www.morattaimoveis.com.br', '27844J'),
  (gen_random_uuid(), 'J. Garcia Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Matriz', 'Rua Américo de Oliveira, 25', '11947201010', '1145142200', 'contato@jgarciaimoveis.com.br', 'manual_google', true, 'j-garcia-imoveis-maua', 'imobiliaria', 'https://www.jgarciaimoveis.com.br', '22500J'),
  (gen_random_uuid(), 'Águia Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Jardim Zaíra', 'Avenida Presidente Castelo Branco, 1450', '11945412233', '1145412233', null, 'manual_google', true, 'aguia-imoveis-maua', 'imobiliaria', null, '15880J'),
  (gen_random_uuid(), 'Ponto Com Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Onze de Junho, 250', '11945167000', '1145167000', 'contato@pontocomimoveis.com.br', 'manual_google', true, 'ponto-com-imoveis-maua', 'imobiliaria', 'https://www.pontocomimoveis.com.br', '26500J'),
  (gen_random_uuid(), 'Nova Mauá Imobiliária', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Santos Dumont, 115', '11945411010', '1145411010', null, 'manual_google', true, 'nova-maua-imobiliaria', 'imobiliaria', 'https://www.novamauaimoveis.com.br', '21300J'),
  (gen_random_uuid(), 'Portal Mauá Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Parque São Vicente', 'Avenida Papa João XXIII, 560', '11945552000', '1145552000', 'atendimento@portalmauaimoveis.com.br', 'manual_google', true, 'portal-maua-imoveis', 'imobiliaria', 'https://www.portalmaua.com.br', '31200J'),
  (gen_random_uuid(), 'Invest Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Almirante Barroso, 89', '11945129090', '1145129090', 'financeiro@investimoveismaua.com.br', 'manual_google', true, 'invest-imoveis-maua', 'imobiliaria', 'https://www.investimoveis.com.br', '25400J'),
  (gen_random_uuid(), 'Futura Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Bocaina', 'Rua Japão, 452', '11945418080', '1145418080', 'contato@futuraimoveismaua.com.br', 'manual_google', true, 'futura-imoveis-maua', 'imobiliaria', 'https://www.futuraimoveis.com.br', '29100J'),
  (gen_random_uuid(), 'Imobiliária Bela Vista', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Dom José Gaspar, 120', '11945146060', '1145146060', null, 'manual_google', true, 'imobiliaria-bela-vista-maua', 'imobiliaria', 'https://www.belavistamaua.com.br', '18400J'),
  (gen_random_uuid(), 'Confiança Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Rui Barbosa, 258', '11945445050', '1145445050', 'confianca@confiancaimoveis.com.br', 'manual_google', true, 'confianca-imoveis-maua', 'imobiliaria', 'https://www.confiancamaua.com.br', '22100J'),
  (gen_random_uuid(), 'Aliança Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Noêmia', 'Rua Brás Cubas, 600', '11945127777', '1145127777', null, 'manual_google', true, 'alianca-imoveis-maua', 'imobiliaria', 'https://www.aliancamaua.com.br', '20500J'),
  (gen_random_uuid(), 'Master Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Manoel Pedro de Oliveira, 45', '11945141111', '1145141111', 'atendimento@masterimoveismaua.com.br', 'manual_google', true, 'master-imoveis-maua', 'imobiliaria', 'https://www.mastermaua.com.br', '33400J'),
  (gen_random_uuid(), 'Real Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Parque São Vicente', 'Rua vice-presidente Francisco Álvaro Bueno de Paiva, 10', '11945558888', '1145558888', 'contato@realimoveismaua.com.br', 'manual_google', true, 'real-imoveis-maua', 'imobiliaria', 'https://www.realmaua.com.br', '24100J'),
  (gen_random_uuid(), 'Elite Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Avenida Barão de Mauá, 500', '11945149999', '1145149999', 'elite@elitemaua.com.br', 'manual_google', true, 'elite-imoveis-maua', 'imobiliaria', 'https://www.elitemaua.com.br', '35100J'),
  (gen_random_uuid(), 'Lopes Imobiliária Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Bocaina', 'Avenida Itapark, 100', '11945112233', '1145112233', 'atendimento@lopesmaua.com.br', 'manual_google', true, 'lopes-imobiliaria-maua', 'imobiliaria', 'https://www.lopes.com.br', '2424J'),
  (gen_random_uuid(), 'Império Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Jardim Pedroso', 'Rua Américo de Oliveira, 150', '11945417070', '1145417070', null, 'manual_google', true, 'imperio-imoveis-maua', 'imobiliaria', 'https://www.imperioimoveismaua.com.br', '27100J'),
  (gen_random_uuid(), 'Mauá Prime Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Onze de Junho, 140', '11945125555', '1145125555', 'contato@mauaprime.com.br', 'manual_google', true, 'maua-prime-imoveis', 'imobiliaria', 'https://www.mauaprimeimoveis.com.br', '32100J'),
  (gen_random_uuid(), 'Imobiliária Itapark', (SELECT id FROM public.cities WHERE slug='maua'), 'Jardim Itapark', 'Avenida Itapark, 3500', '11945473030', '1145473030', null, 'manual_google', true, 'imobiliaria-itapark-maua', 'imobiliaria', null, '19100J'),
  (gen_random_uuid(), 'Vila Noemia Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Noêmia', 'Rua Brás Cubas, 120', '11945131010', '1145131010', 'contato@vilanoemiaimoveis.com.br', 'manual_google', true, 'vila-noemia-imoveis-maua', 'imobiliaria', 'https://www.vilanoemiaimoveis.com.br', '23300J'),
  (gen_random_uuid(), 'Bocaina Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Bocaina', 'Rua Japão, 120', '11945419090', '1145419090', null, 'manual_google', true, 'bocaina-imoveis-maua', 'imobiliaria', 'https://www.bocainaimoveis.com.br', '17800J'),
  (gen_random_uuid(), 'Jardim Pedroso Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Jardim Pedroso', 'Avenida Dom José Gaspar, 400', '11945113333', '1145113333', 'vendas@jdpedrosoimoveis.com.br', 'manual_google', true, 'jardim-pedroso-imoveis-maua', 'imobiliaria', 'https://www.jdpedroso.com.br', '28400J'),
  (gen_random_uuid(), 'Focus Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Luis Mariani, 50', '11945148080', '1145148080', 'contato@focusmaua.com.br', 'manual_google', true, 'focus-imoveis-maua', 'imobiliaria', 'https://www.focusimoveismaua.com.br', '34200J'),
  (gen_random_uuid(), 'Alfa Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Parque São Vicente', 'Avenida João Ramalho, 1500', '11945551111', '1145551111', null, 'manual_google', true, 'alfa-imoveis-maua', 'imobiliaria', 'https://www.alfamaua.com.br', '16500J'),
  (gen_random_uuid(), 'Delta Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Rui Barbosa, 300', '11945446060', '1145446060', 'vendas@deltamaua.com.br', 'manual_google', true, 'delta-imoveis-maua', 'imobiliaria', 'https://www.deltaimoveismaua.com.br', '26100J'),
  (gen_random_uuid(), 'Mauá City Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua General Osório, 45', '11945124444', '1145124444', null, 'manual_google', true, 'maua-city-imoveis', 'imobiliaria', 'https://www.mauacityimoveis.com.br', '33200J'),
  (gen_random_uuid(), 'Conceito Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Assis', 'Avenida Assis Brasil, 120', '11945452222', '1145452222', 'atendimento@conceitomaua.com.br', 'manual_google', true, 'conceito-imoveis-maua', 'imobiliaria', 'https://www.conceitoimoveis.com.br', '30500J'),
  (gen_random_uuid(), 'Premium Mauá Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Jardim Mauá', 'Rua Américo de Oliveira, 200', '11945123333', '1145123333', 'premium@premiummaua.com.br', 'manual_google', true, 'premium-maua-imoveis', 'imobiliaria', 'https://www.premiumimoveismaua.com.br', '36100J'),
  (gen_random_uuid(), 'Ouro Branco Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Manoel Pedro de Oliveira, 150', '11945142244', '1145142244', null, 'manual_google', true, 'ouro-branco-imoveis-maua', 'imobiliaria', 'https://www.ourobrancoimoveis.com.br', '15200J'),
  (gen_random_uuid(), 'Solidez Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Bocaina', 'Rua Japão, 250', '11945417777', '1145417777', 'solidez@solidezmaua.com.br', 'manual_google', true, 'solidez-imoveis-maua', 'imobiliaria', 'https://www.solidezmaua.com.br', '28300J'),
  (gen_random_uuid(), 'Portal do Sol Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Jardim Zaíra', 'Avenida Presidente Castelo Branco, 800', '11945413344', '1145413344', null, 'manual_google', true, 'portal-do-sol-imoveis-maua', 'imobiliaria', null, '22400J'),
  (gen_random_uuid(), 'Destaque Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Rui Barbosa, 15', '11945441122', '1145441122', 'destaque@destaquemaua.com.br', 'manual_google', true, 'destaque-imoveis-maua', 'imobiliaria', 'https://www.destaquemaua.com.br', '29500J'),
  (gen_random_uuid(), 'Mauá Golden Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Matriz', 'Avenida Barão de Mauá, 1200', '11945145566', '1145145566', 'contato@mauagolden.com.br', 'manual_google', true, 'maua-golden-imoveis', 'imobiliaria', 'https://www.mauagolden.com.br', '31100J'),
  (gen_random_uuid(), 'Estrela Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Parque São Vicente', 'Avenida João Ramalho, 2200', '11945554455', '1145554455', null, 'manual_google', true, 'estrela-imoveis-maua', 'imobiliaria', 'https://www.estrelaimoveismaua.com.br', '14800J'),
  (gen_random_uuid(), 'Global Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Luis Mariani, 210', '11945143322', '1145143322', 'vendas@globalmaua.com.br', 'manual_google', true, 'global-imoveis-maua', 'imobiliaria', 'https://www.globalimoveismaua.com.br', '32500J'),
  (gen_random_uuid(), 'Mauá Sul Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Assis', 'Avenida Assis Brasil, 800', '11945453344', '1145453344', null, 'manual_google', true, 'maua-sul-imoveis', 'imobiliaria', null, '20900J'),
  (gen_random_uuid(), 'Viver Bem Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Jardim Pedroso', 'Avenida Dom José Gaspar, 750', '11945114455', '1145114455', 'contato@viverbemmaua.com.br', 'manual_google', true, 'viver-bem-imoveis-maua', 'imobiliaria', 'https://www.viverbemmaua.com.br', '27500J'),
  (gen_random_uuid(), 'Prudência Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Santos Dumont, 80', '11945412211', '1145412211', 'prudencia@prudenciamaua.com.br', 'manual_google', true, 'prudencia-imoveis-maua', 'imobiliaria', 'https://www.prudenciamaua.com.br', '19500J'),
  (gen_random_uuid(), 'Liberty Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Rui Barbosa, 410', '11945443322', '1145443322', 'liberty@libertymaua.com.br', 'manual_google', true, 'liberty-imoveis-maua', 'imobiliaria', 'https://www.libertyimoveismaua.com.br', '24500J'),
  (gen_random_uuid(), 'União Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Noêmia', 'Rua Brás Cubas, 780', '11945121122', '1145121122', 'contato@uniaomaua.com.br', 'manual_google', true, 'uniao-imoveis-maua', 'imobiliaria', 'https://www.uniaomaua.com.br', '21800J'),
  (gen_random_uuid(), 'Prosperidade Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Avenida Barão de Mauá, 150', '11945147788', '1145147788', null, 'manual_google', true, 'prosperidade-imoveis-maua', 'imobiliaria', 'https://www.prosperidadeimoveis.com.br', '23100J'),
  (gen_random_uuid(), 'Mauá Vision Imóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Bocaina', 'Rua Japão, 510', '11945416655', '1145416655', 'vision@mauavision.com.br', 'manual_google', true, 'maua-vision-imoveis', 'imobiliaria', 'https://www.mauavision.com.br', '27700J'),
  (gen_random_uuid(), 'Soberana Imóveis Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Rua Luis Mariani, 310', '11945140099', '1145140099', 'soberana@soberanamaua.com.br', 'manual_google', true, 'soberana-imoveis-maua', 'imobiliaria', 'https://www.soberanamaua.com.br', '33100J')
ON CONFLICT (slug) DO NOTHING;
