-- 1. Ensure City Exists (Santo André)
INSERT INTO public.cities (name, slug, state)
VALUES ('Santo André', 'santo-andre', 'SP')
ON CONFLICT (slug) DO NOTHING;

-- 2. Insert Providers (Automotive)
-- Using gen_random_uuid() for IDs
INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  (gen_random_uuid(), 'Moove Veículos', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Vila Pires', 'Avenida Dom Pedro I, 1650', '11947285145', '11947285145', 'contato@mooveveiculos.com.br', 'manual_google', true, 'moove-veiculos-santo-andre', 'automoveis', 'https://www.mooveveiculos.com.br', null),
  (gen_random_uuid(), 'Davema Multimarcas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Vila Pires', 'Av. Dom Pedro I, 1666', '11987932456', '1144558877', 'vendas@davema.com.br', 'manual_google', true, 'davema-multimarcas-santo-andre', 'automoveis', 'https://www.davema.com.br', null),
  (gen_random_uuid(), 'Vigorito Chevrolet', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Tamanduateí 3', 'Av. Industrial, 1000', '1149799000', '1149799000', 'contato@vigoritogm.com.br', 'manual_google', true, 'vigorito-chevrolet-santo-andre', 'automoveis', 'https://www.vigoritogm.com.br', null),
  (gen_random_uuid(), 'Fiat Savol', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Casa Branca', 'Av. Artur de Queirós, 414', '1133191000', '1133191000', 'atendimento@savol.com.br', 'manual_google', true, 'fiat-savol-santo-andre', 'automoveis', 'https://www.savol.com.br', null),
  (gen_random_uuid(), 'Hyundai Caoa', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Casa Branca', 'Av. Artur de Queirós, 651', '1144334500', '1144334500', 'contato@caoa.com.br', 'manual_google', true, 'hyundai-caoa-santo-andre', 'automoveis', 'https://www.caoa.com.br', null),
  (gen_random_uuid(), 'Honda André Ribeiro', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Centro', 'Av. Ramiro Colleoni, 377', '1132383200', '1132383200', 'contato@andreribeiro.com.br', 'manual_google', true, 'honda-andre-ribeiro-santo-andre', 'automoveis', 'https://www.andreribeiro.com.br', null),
  (gen_random_uuid(), 'Jeep Destaque', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Campestre', 'Av. Dom Pedro II, 2089', '1144287420', '1144287420', 'contato@jeepdestaque.com.br', 'manual_google', true, 'jeep-destaque-santo-andre', 'automoveis', 'https://www.destaquejeep.com.br', null),
  (gen_random_uuid(), 'Kia Savol', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Casa Branca', 'Avenida Artur de Queiros, 555', '1143311000', '1143311000', 'kia@savol.com.br', 'manual_google', true, 'kia-savol-santo-andre', 'automoveis', 'https://www.savolkia.com.br', null),
  (gen_random_uuid(), 'Nissan Armando', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Campestre', 'Av. D. Pedro II, 2449', '1127616363', '1127616363', 'contato@armandoveiculos.com.br', 'manual_google', true, 'nissan-armando-santo-andre', 'automoveis', 'https://www.armandoveiculos.com.br', null),
  (gen_random_uuid(), 'Citroën Montparnasse', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Casa Branca', 'Av. Artur de Queirós, 424', '1144336700', '1144336700', 'citroen@montparnasse.com.br', 'manual_google', true, 'citroen-montparnasse-santo-andre', 'automoveis', null, null),
  (gen_random_uuid(), 'Chery D21 Motors', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Casa Branca', 'Av. Artur de Queirós, 542', '11974571778', '11974571778', 'contato@d21motors.com.br', 'manual_google', true, 'chery-d21-motors-santo-andre', 'automoveis', 'https://www.d21motors.com.br', null),
  (gen_random_uuid(), 'Autobim Multimarcas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Vila Pires', 'Avenida Dom Pedro I, 905', '11947230000', '1144510000', 'autobim@autobim.com.br', 'manual_google', true, 'autobim-multimarcas-santo-andre', 'automoveis', 'https://www.autobim.com.br', null),
  (gen_random_uuid(), 'Via Certa Multimarcas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779272', '1149779272', 'contato@viacertamultimarcas.com.br', 'manual_google', true, 'via-certa-multimarcas-santo-andre', 'automoveis', 'https://www.viacertamultimarcas.com.br', null),
  (gen_random_uuid(), 'Fênice Multimarcas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Vila Pires', 'Rua Miguel Prisco, 30', '1144519999', '1144519999', 'fenice@fenice.com.br', 'manual_google', true, 'fenice-multimarcas-santo-andre', 'automoveis', 'https://www.fenice.com.br', null),
  (gen_random_uuid(), 'Dom Multimarcas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Vila Pires', 'Rua Miguel Prisco, 150', '1123252503', '1123252503', 'contato@dommultimarcas.com.br', 'manual_google', true, 'dom-multimarcas-santo-andre', 'automoveis', 'https://www.dommultimarcas.com.br', null),
  (gen_random_uuid(), 'Century Automóveis', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Vila Alzira', 'Rua Carijós, 1500', '1144513322', '1144513322', 'contato@centuryautomoveis.com.br', 'manual_google', true, 'century-automoveis-santo-andre', 'automoveis', 'https://www.centuryautomoveis.com.br', null),
  (gen_random_uuid(), 'Santo André Automóveis', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Centro', 'Rua Coronel Alfredo Flaquer, 722', '11947138816', '1144362709', 'vendas@santoandreautomoveis.com.br', 'manual_google', true, 'santo-andre-automoveis', 'automoveis', 'https://www.santoandreautomoveis.com.br', null),
  (gen_random_uuid(), 'Renault Santo André', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Campestre', 'Av. Dom Pedro II, 2429', '1127616400', '1127616400', 'renault@armandoveiculos.com.br', 'manual_google', true, 'renault-santo-andre', 'automoveis', 'https://www.armandoveiculos.com.br', null),
  (gen_random_uuid(), 'Alpha Motors', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@alphamotors.com.br', 'manual_google', true, 'alpha-motors-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Arizona Motors', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@arizonamotors.com.br', 'manual_google', true, 'arizona-motors-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Auto Fluxo', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@autofluxo.com.br', 'manual_google', true, 'auto-fluxo-santo-andre', 'automoveis', 'https://www.autofluxomultimarcas.com.br', null),
  (gen_random_uuid(), 'Automaz Multimarcas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@automaz.com.br', 'manual_google', true, 'automaz-multimarcas-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Blascar Multimarcas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'vendas@blascarmultimarcas.com.br', 'manual_google', true, 'blascar-multimarcas-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Boxter Multimarcas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@boxtermultimarcas.com.br', 'manual_google', true, 'boxter-multimarcas-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Canaã ABC Automóveis', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@canaaabc.com.br', 'manual_google', true, 'canaa-abc-automoveis-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Carmax Autos', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'vendas@carmaxautos.com.br', 'manual_google', true, 'carmax-autos-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Cesco Car Multimarcas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@cescocar.com.br', 'manual_google', true, 'cesco-car-multimarcas-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Davanti Multimarcas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@davanti.com.br', 'manual_google', true, 'davanti-multimarcas-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Evoluir Veículos', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@evoluirveiculos.com.br', 'manual_google', true, 'evoluir-veiculos-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Felisa Multimarcas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@felisamultimarcas.com.br', 'manual_google', true, 'felisa-multimarcas-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Front Motors', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@frontmotors.com.br', 'manual_google', true, 'front-motors-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Garage Cars', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@garagecars.com.br', 'manual_google', true, 'garage-cars-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Giba Multimarcas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@gibamultimarcas.com.br', 'manual_google', true, 'giba-multimarcas-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Global Car Store', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@globalcarstore.com.br', 'manual_google', true, 'global-car-store-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Grupo Polerá', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@grupopolera.com.br', 'manual_google', true, 'grupo-polera-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'HR Premium', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '1149779000', '1149779000', 'contato@hrpremium.com.br', 'manual_google', true, 'hr-premium-santo-andre', 'automoveis', 'https://www.autoshoppingglobal.com.br', null),
  (gen_random_uuid(), 'Quality Multimarcas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Capuava', 'Avenida dos Estados, 8000 (Auto Shopping Global)', '11940290319', '11940290319', 'contato@qualitycarmultimarcas.com.br', 'manual_google', true, 'quality-multimarcas-santo-andre', 'automoveis', 'https://www.qualitycarmultimarcas.com.br', null),
  (gen_random_uuid(), 'Zero Berto Car', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Vila Pires', 'Rua Miguel Prisco, 300', '1144510000', '1144510000', 'contato@zerobertocar.com.br', 'manual_google', true, 'zero-berto-car-santo-andre', 'automoveis', 'https://www.zerobertocar.com.br', null),
  (gen_random_uuid(), 'Nevada Multimarcas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Vila Pires', 'Avenida Dom Pedro I, 1500', '1144519999', '1144519999', 'contato@nevadamultimarcas.com.br', 'manual_google', true, 'nevada-multimarcas-santo-andre', 'automoveis', 'https://www.nevadamultimarcas.com.br', null),
  (gen_random_uuid(), 'Carrera Acelera Veículos', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Campestre', 'Av. Dom Pedro II, 2000', '1144287420', '1144287420', 'contato@carrera.com.br', 'manual_google', true, 'carrera-acelera-veiculos-santo-andre', 'automoveis', 'https://www.carrera.com.br', null)
ON CONFLICT (slug) DO NOTHING;
