-- 1. Ensure City Exists (São Caetano do Sul)
INSERT INTO public.cities (name, slug, state)
VALUES ('São Caetano do Sul', 'sao-caetano-do-sul', 'SP')
ON CONFLICT (slug) DO NOTHING;

-- 2. Insert Providers (Automotive)
-- Using gen_random_uuid() for IDs
INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  (gen_random_uuid(), 'São Caetano Automóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santo Antônio', 'Avenida Goiás, 981', '11992024000', '1142214000', 'contato@saocaetanoautomoveis.com.br', 'manual_google', true, 'sao-caetano-automoveis-scs', 'automoveis', 'https://www.saocaetanoautomoveis.com.br', null),
  (gen_random_uuid(), 'Theoria Veículos', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Av. Goiás, 2465', '11953271051', '1127592484', 'contato@theoriaveiculos.com.br', 'manual_google', true, 'theoria-veiculos-scs', 'automoveis', 'https://www.theoriaveiculos.com.br', null),
  (gen_random_uuid(), 'Fiat Savol', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Av. Goiás, 3040', '1133811000', '1133811000', 'contato@savol.com.br', 'manual_google', true, 'fiat-savol-scs', 'automoveis', 'https://www.savol.com.br', null),
  (gen_random_uuid(), 'Chery D21 Motors', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santo Antônio', 'Av. Goiás, 1910', '1142236551', '1142236551', 'contato@d21motors.com.br', 'manual_google', true, 'chery-d21-motors-scs', 'automoveis', 'https://www.d21motors.com.br', null),
  (gen_random_uuid(), 'Chevrolet Primarca', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Centro', 'Rua Baraldi, 275', '1121720300', '1121720300', 'contato@primarca.com.br', 'manual_google', true, 'chevrolet-primarca-scs', 'automoveis', 'https://www.primarca.com.br', null),
  (gen_random_uuid(), 'Ford Mix', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Centro', 'Rua Alagoas, 41', '1142249000', '1142249000', 'contato@fordmix.com.br', 'manual_google', true, 'ford-mix-scs', 'automoveis', 'https://www.fordmix.com.br', null),
  (gen_random_uuid(), 'Honda Mix', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Centro', 'Av. Guido Aliberti, 331', '1142249009', '1142249009', 'contato@hondamix.com.br', 'manual_google', true, 'honda-mix-scs', 'automoveis', 'https://www.hondamix.com.br', null),
  (gen_random_uuid(), 'Hyundai Caoa', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Av. Goiás, 120', '1147700000', '1147700000', 'contato@caoa.com.br', 'manual_google', true, 'hyundai-caoa-scs', 'automoveis', 'https://www.caoa.com.br', null),
  (gen_random_uuid(), 'Renault Armando', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santo Antônio', 'Av. Sen. Roberto Símonsen, 365', '1147638080', '1147638080', 'contato@armandorenault.com.br', 'manual_google', true, 'renault-armando-scs', 'automoveis', 'https://www.armandorenault.com.br', null),
  (gen_random_uuid(), 'Toyota Tsusho', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santo Antônio', 'Av. Guido Aliberti, 1111', '1142240555', '1142240555', 'contato@toyotatsusho.com.br', 'manual_google', true, 'toyota-tsusho-scs', 'automoveis', 'https://www.toyotatsusho.com.br', null),
  (gen_random_uuid(), 'Volkswagen Diauto', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Av. Goiás, 3499', '1142258500', '1142258500', 'contato@diauto.com.br', 'manual_google', true, 'volkswagen-diauto-scs', 'automoveis', 'https://www.diauto.com.br', null),
  (gen_random_uuid(), 'Scuderia Veículos', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Avenida Goiás, 2526', '1142219595', '1142219595', 'contato@scuderiaveiculos.com.br', 'manual_google', true, 'scuderia-veiculos-scs', 'automoveis', null, null),
  (gen_random_uuid(), '355 Automóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Centro', 'Rua Alagoas, 358', '1142215438', '1142215438', 'contato@355automoveis.com.br', 'manual_google', true, '355-automoveis-scs', 'automoveis', null, null),
  (gen_random_uuid(), 'Cavalcante Veículos', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santo Antônio', 'Avenida Goiás, 810', '1142295560', '1142295560', 'contato@cavalcanteveiculos.com.br', 'manual_google', true, 'cavalcante-veiculos-scs', 'automoveis', null, null),
  (gen_random_uuid(), 'Auto Giros Motors', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Olímpico', 'Praça Jaime Pereira Galo, 78', '1135651519', '1135651519', 'contato@autogirosmotors.com.br', 'manual_google', true, 'auto-giros-motors-scs', 'automoveis', null, null),
  (gen_random_uuid(), 'Abc Autos', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Avenida Presidente Kennedy, 3168', '1142329546', '1142329546', 'contato@abcautos.com.br', 'manual_google', true, 'abc-autos-scs', 'automoveis', null, null),
  (gen_random_uuid(), 'Dirvel Veículos', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Avenida Goiás, 2169', '1142296899', '1142296899', 'contato@dirvel.com.br', 'manual_google', true, 'dirvel-veiculos-scs', 'automoveis', null, null),
  (gen_random_uuid(), 'Ferreira Automóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Avenida Goiás, 2170', '1142211266', '1142211266', 'contato@ferreiraautomoveis.com.br', 'manual_google', true, 'ferreira-automoveis-scs', 'automoveis', null, null),
  (gen_random_uuid(), 'Alpha Multimarcas', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Nova Gerty', 'Rua Nelly Pellegrino, 450', '11976500776', '1143188857', 'contato@alphamultimarcas.com.br', 'manual_google', true, 'alpha-multimarcas-scs', 'automoveis', null, null),
  (gen_random_uuid(), 'Sunny Multimarcas', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Av. Goiás, 391', '11947785696', '1141772871', 'contato@sunnymultimarcas.com.br', 'manual_google', true, 'sunny-multimarcas-scs', 'automoveis', 'https://www.sunnymultimarcas.com.br', null),
  (gen_random_uuid(), 'Globo Car 99', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Fundação', 'Av. do Estado, 100 (Auto Shopping Imigrantes)', '1142261000', '1142261000', 'contato@globocar.com.br', 'manual_google', true, 'globo-car-99-scs', 'automoveis', 'https://www.autoshoppingimigrantes.com.br', null),
  (gen_random_uuid(), 'Lavo Tour Motors', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Fundação', 'Av. do Estado, 100 (Auto Shopping Imigrantes)', '1142261000', '1142261000', 'contato@lavotour.com.br', 'manual_google', true, 'lavo-tour-motors-scs', 'automoveis', 'https://www.autoshoppingimigrantes.com.br', null),
  (gen_random_uuid(), 'Canever Veículos', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Fundação', 'Av. do Estado, 100 (Auto Shopping Imigrantes)', '1142261000', '1142261000', 'contato@canever.com.br', 'manual_google', true, 'canever-veiculos-scs', 'automoveis', 'https://www.autoshoppingimigrantes.com.br', null),
  (gen_random_uuid(), 'Pistarell Automóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Fundação', 'Av. do Estado, 100 (Auto Shopping Imigrantes)', '1142261000', '1142261000', 'contato@pistarell.com.br', 'manual_google', true, 'pistarell-automoveis-scs', 'automoveis', 'https://www.autoshoppingimigrantes.com.br', null)
ON CONFLICT (slug) DO NOTHING;
