-- 28. Insert Handyman (Marido de Aluguel) Providers (São Caetano do Sul)

INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  (gen_random_uuid(), 'Marido de Aluguel Hidrotex', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11948931000', '1141144004', 'contato@maridodealuguel.adm.br', 'manual_google', true, 'marido-de-aluguel-hidrotex-scs', 'marido_aluguel', 'https://www.maridodealuguel.adm.br', null),
  (gen_random_uuid(), 'Guima Service', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11916780108', '11916780108', 'contato@guimaservice.com.br', 'manual_google', true, 'guima-service-scs', 'marido_aluguel', 'https://www.dfgmaridodealuguel.com.br', null),
  (gen_random_uuid(), 'Marido de Aluguel SOS', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11955833112', '11955833112', 'contato@maridodealuguelsos.com.br', 'manual_google', true, 'marido-de-aluguel-sos-scs', 'marido_aluguel', 'https://www.maridodealuguelsos.com.br', null),
  (gen_random_uuid(), 'Jorge Ravelli', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11995018109', '11995018109', null, 'manual_google', true, 'jorge-ravelli-scs', 'marido_aluguel', null, null),
  (gen_random_uuid(), 'Doutor Resolve', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', null, null, 'contato@doutorresolve.com.br', 'manual_google', true, 'doutor-resolve-scs', 'marido_aluguel', 'https://www.doutorresolve.com.br', null),
  (gen_random_uuid(), 'Encanador 24hs São Caetano', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11986154000', '11986154000', 'contato@encanador24horas.srv.br', 'manual_google', true, 'encanador-24hs-sao-caetano', 'marido_aluguel', 'https://www.encanador24horas.srv.br', null),
  (gen_random_uuid(), 'Eletricista 24hs São Caetano', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11948082000', '11948082000', 'contato@eletricista24hs.adm.br', 'manual_google', true, 'eletricista-24hs-sao-caetano', 'eletricista', 'https://www.eletricista24hs.adm.br', null),
  (gen_random_uuid(), 'CPS Manutenções', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11986347827', '11986347827', 'contato@cpsmanutencoes.com', 'manual_google', true, 'cps-manutencoes-scs', 'encanador', 'https://www.cpsmanutencoes.com', null),
  (gen_random_uuid(), 'Montador de Móveis Águia', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11981582253', '11961498143', 'contato@aguiamontagemdemoveisbr.com.br', 'manual_google', true, 'montador-moveis-aguia-scs', 'marido_aluguel', 'https://www.aguiamontagemdemoveisbr.com.br', null),
  (gen_random_uuid(), 'Destaque Montagem', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11978546109', '11978546109', 'contato@destaquemontagemdemoveis.com.br', 'manual_google', true, 'destaque-montagem-scs', 'marido_aluguel', 'https://www.destaquemontagemdemoveis.com.br', null)
ON CONFLICT (slug) DO NOTHING;
