-- 34. Insert Electricians (Eletricista) Providers (São Bernardo do Campo)

INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  (gen_random_uuid(), 'Eletricista São Bernardo do Campo', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'São Bernardo do Campo', 'São Bernardo do Campo/SP', '11948931000', '5511948931000', 'contato@eletricista24hs.srv.br', 'manual_google', true, 'eletricista-sao-bernardo-do-campo', 'eletricista', 'https://www.eletricista24hs.srv.br', null),
  (gen_random_uuid(), 'Eletricista Bonelli', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'São Bernardo do Campo', 'São Bernardo do Campo/SP', '11987700860', '11987700860', 'contato@eletricistabonelli.com.br', 'manual_google', true, 'eletricista-bonelli-sbc', 'eletricista', 'https://www.eletricistabonelli.com.br', null),
  (gen_random_uuid(), 'Eletricista em São Bernardo', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'São Bernardo do Campo', 'São Bernardo do Campo/SP', '11986113565', '11986113565', 'contato@eletricistasaobernardo.com.br', 'manual_google', true, 'eletricista-em-sao-bernardo', 'eletricista', 'https://www.eletricistasaobernardo.com.br', null),
  (gen_random_uuid(), 'Silva Eletricista', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'São Bernardo do Campo', 'São Bernardo do Campo/SP', '11994593320', '11994593320', null, 'manual_google', true, 'silva-eletricista-sbc', 'eletricista', 'https://www.olx.com.br', null),
  (gen_random_uuid(), 'GetNinjas - Eletricistas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'São Bernardo do Campo', 'São Bernardo do Campo/SP', null, null, 'contato@getninjas.com.br', 'manual_google', true, 'getninjas-eletricistas-sbc', 'eletricista', 'https://www.getninjas.com.br', null),
  (gen_random_uuid(), 'Triider - Eletricistas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'São Bernardo do Campo', 'São Bernardo do Campo/SP', null, null, 'contato@triider.com.br', 'manual_google', true, 'triider-eletricistas-sbc', 'eletricista', 'https://www.triider.com.br', null),
  (gen_random_uuid(), 'Cronoshare - Eletricistas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'São Bernardo do Campo', 'São Bernardo do Campo/SP', null, null, 'contato@cronoshare.com.br', 'manual_google', true, 'cronoshare-eletricistas-sbc', 'eletricista', 'https://www.cronoshare.com.br', null)
ON CONFLICT (slug) DO NOTHING;
