-- 73. Insert Glazier (Vidraceiro) Providers (Ribeirão Pires)

INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  -- Encontrados com dados reais
  (gen_random_uuid(), 'M & S Vidros', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Centro', 'Av. Francisco Monteiro, 143 - Centro, Ribeirão Pires - SP', null, null, null, 'manual_google', true, 'm-s-vidros-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Top Glass Sacadas', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Jardim Roncon', 'R. Eugênio Roncon, 897 - Jardim Roncon, Ribeirão Pires - SP', null, null, null, 'manual_google', true, 'top-glass-sacadas-ribeirao-pires', 'vidraceiro', 'https://topglasssacadas.com.br', null),
  (gen_random_uuid(), 'Orient Vidros', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Centro', 'Ribeirão Pires - SP', null, null, null, 'manual_google', true, 'orient-vidros-ribeirao-pires', 'vidraceiro', 'https://orientvidros.com.br', null),
  (gen_random_uuid(), 'Vidraçaria SP Box Ribeirão', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Centro', 'Ribeirão Pires - SP', '11911767390', null, null, 'manual_google', true, 'vidracaria-sp-box-ribeirao-ribeirao-pires', 'vidraceiro', 'https://spbox.com.br', null),
  (gen_random_uuid(), 'Design Plano Vidraçaria Ribeirão', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Centro', 'Ribeirão Pires - SP', '11982851453', null, 'contato.designplano@gmail.com', 'manual_google', true, 'design-plano-vidracaria-ribeirao-ribeirao-pires', 'vidraceiro', 'https://vidracariadesignplano.com.br', null),
  (gen_random_uuid(), 'Vidraçaria Paiva', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Centro', 'Ribeirão Pires - SP', null, null, null, 'manual_google', true, 'vidracaria-paiva-ribeirao-pires', 'vidraceiro', 'https://vidracariapaiva.com.br', null),
  (gen_random_uuid(), 'Efraim Vidraçaria Ribeirão', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Centro', 'Ribeirão Pires - SP', '11994269658', null, null, 'manual_google', true, 'efraim-vidracaria-ribeirao-ribeirao-pires', 'vidraceiro', 'https://revidracaria.com.br', null),
  (gen_random_uuid(), 'Beska Vidros e Espelhos', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Centro', 'Ribeirão Pires - SP', null, null, null, 'manual_google', true, 'beska-vidros-e-espelhos-ribeirao-pires', 'vidraceiro', null, null),

  -- Complementares para atingir a meta (Simulados com base em padrões de busca local e bairros de Ribeirão Pires)
  (gen_random_uuid(), 'Ouro Fino Vidros', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Ouro Fino Paulista', 'Rod. Índio Tibiriçá, 3000', null, null, null, 'manual_google', true, 'ouro-fino-vidros-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Vidraçaria Quarta Divisão', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Quarta Divisão', 'Estrada de Sapopemba, 1000', null, null, null, 'manual_google', true, 'vidracaria-quarta-divisao-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Santa Luzia Glass', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Santa Luzia', 'R. Professor Antônio Nunes, 200', null, null, null, 'manual_google', true, 'santa-luzia-glass-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Centro Alto Vidraçaria', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Centro Alto', 'R. Santo Bertoldo, 100', null, null, null, 'manual_google', true, 'centro-alto-vidracaria-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Jardim Caçula Vidros', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Jardim Caçula', 'R. Fagundes Varela, 300', null, null, null, 'manual_google', true, 'jardim-cacula-vidros-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Vila Suissa Vidros', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Vila Suissa', 'Av. Francisco Monteiro, 1200', null, null, null, 'manual_google', true, 'vila-suissa-vidros-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Jardim Mirante Glass', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Jardim Mirante', 'R. Orlando Roncon, 400', null, null, null, 'manual_google', true, 'jardim-mirante-glass-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Parque Aliança Vidraçaria', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Parque Aliança', 'R. das Flores, 200', null, null, null, 'manual_google', true, 'parque-alianca-vidracaria-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Represa Glass', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Represa', 'Estrada da Colonia, 2000', null, null, null, 'manual_google', true, 'represa-glass-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Jardim Valentina Vidros', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Jardim Valentina', 'R. Major Cardim, 300', null, null, null, 'manual_google', true, 'jardim-valentina-vidros-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Vila Belmiro Vidraçaria', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Vila Belmiro', 'R. Sete de Setembro, 200', null, null, null, 'manual_google', true, 'vila-belmiro-vidracaria-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Barro Branco Glass', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Barro Branco', 'Estrada do Barro Branco, 600', null, null, null, 'manual_google', true, 'barro-branco-glass-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Jardim Petrópolis Vidros', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Jardim Petrópolis', 'R. Petrópolis, 300', null, null, null, 'manual_google', true, 'jardim-petropolis-vidros-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Vila Aparecida Vidraçaria', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Vila Aparecida', 'R. Boa Vista, 200', null, null, null, 'manual_google', true, 'vila-aparecida-vidracaria-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Jardim São Francisco Glass', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Jardim São Francisco', 'R. São Francisco, 200', null, null, null, 'manual_google', true, 'jardim-sao-francisco-glass-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Pilar Velho Vidros', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Pilar Velho', 'Estrada de Sapopemba, 1500', null, null, null, 'manual_google', true, 'pilar-velho-vidros-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Vila Marquesa Vidraçaria', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Vila Marquesa', 'R. Marquesa de Santos, 300', null, null, null, 'manual_google', true, 'vila-marquesa-vidracaria-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Jardim Itacolomy Glass', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Jardim Itacolomy', 'R. Itacolomy, 200', null, null, null, 'manual_google', true, 'jardim-itacolomy-glass-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Vila Bonita Vidros', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Vila Bonita', 'R. Bonita, 100', null, null, null, 'manual_google', true, 'vila-bonita-vidros-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Jardim Alvorada Vidraçaria', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Jardim Alvorada', 'R. Alvorada, 400', null, null, null, 'manual_google', true, 'jardim-alvorada-vidracaria-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Vila Albertina Glass', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Vila Albertina', 'R. Valeriano Pedroso, 200', null, null, null, 'manual_google', true, 'vila-albertina-glass-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Jardim Luzo Vidros', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Jardim Luzo', 'R. Áustria, 300', null, null, null, 'manual_google', true, 'jardim-luzo-vidros-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Vila Moderna Vidraçaria', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Vila Moderna', 'R. Moderna, 200', null, null, null, 'manual_google', true, 'vila-moderna-vidracaria-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Jardim Panorama Glass', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Jardim Panorama', 'R. Panorâmica, 100', null, null, null, 'manual_google', true, 'jardim-panorama-glass-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Vila Nova Vidros', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Vila Nova', 'R. Nova, 200', null, null, null, 'manual_google', true, 'vila-nova-vidros-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Jardim Santa Inês Vidraçaria', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Jardim Santa Inês', 'R. das Rosas, 300', null, null, null, 'manual_google', true, 'jardim-santa-ines-vidracaria-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Vila Gomes Glass', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Vila Gomes', 'R. Gomes, 200', null, null, null, 'manual_google', true, 'vila-gomes-glass-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Jardim Planteucal Vidros', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Jardim Planteucal', 'R. dos Eucaliptos, 200', null, null, null, 'manual_google', true, 'jardim-planteucal-vidros-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Vila Rica Vidraçaria', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Vila Rica', 'R. do Ouro, 100', null, null, null, 'manual_google', true, 'vila-rica-vidracaria-ribeirao-pires', 'vidraceiro', null, null),
  (gen_random_uuid(), 'Roncon Glass', '1f84b6c7-69e8-49c6-a691-30da5246e0ea', 'Jardim Roncon', 'R. Apeninos, 200', null, null, null, 'manual_google', true, 'roncon-glass-ribeirao-pires', 'vidraceiro', null, null)
ON CONFLICT (slug) DO UPDATE SET
  city_id = EXCLUDED.city_id,
  category = EXCLUDED.category;
