-- 96. Insert Pest Control (Dedetizadora) Providers (Santo André)

INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  -- Encontrados com dados reais
  (gen_random_uuid(), 'EccoClean Dedetizadora', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Centro', 'Santo André - SP', null, null, null, 'manual_google', true, 'eccoclean-dedetizadora-santo-andre', 'dedetizadora', 'https://eccocleandedetizacao.com.br', null),
  (gen_random_uuid(), 'Protec Pragas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Centro', 'Santo André - SP', null, null, null, 'manual_google', true, 'protec-pragas-santo-andre', 'dedetizadora', 'https://protecpragas.com.br', null),
  (gen_random_uuid(), 'DTIZA Controle de Pragas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Centro', 'Santo André - SP', null, null, null, 'manual_google', true, 'dtiza-controle-de-pragas-santo-andre', 'dedetizadora', 'https://dtiza.com.br', null),
  (gen_random_uuid(), 'EcoServiços Dedetizadora', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Centro', 'Santo André - SP', null, '1151820000', null, 'manual_google', true, 'ecoservicos-dedetizadora-santo-andre', 'dedetizadora', 'https://ecoservicos.com.br', null),
  (gen_random_uuid(), 'Lunar Dedetizadora', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Centro', 'Santo André - SP', null, null, null, 'manual_google', true, 'lunar-dedetizadora-santo-andre', 'dedetizadora', 'https://lunardedetizadora.com.br', null),
  (gen_random_uuid(), 'Dedetizadora Menor Preço', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Centro', 'Santo André - SP', '11913628000', null, null, 'manual_google', true, 'dedetizadora-menor-preco-santo-andre', 'dedetizadora', 'https://dedetizadoramenorpreco.com.br', null),
  (gen_random_uuid(), 'TDP Pragas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Vila Valparaíso', 'Rua Andradina, 90', null, null, null, 'manual_google', true, 'tdp-pragas-santo-andre', 'dedetizadora', 'https://tdppragas.com.br', null),
  (gen_random_uuid(), 'Mygg Dedetizadora', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Centro', 'Santo André - SP', null, null, null, 'manual_google', true, 'mygg-dedetizadora-santo-andre', 'dedetizadora', 'https://myggdedetizadora.com.br', null),
  (gen_random_uuid(), 'Dedetizadora Lava Imper', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Centro', 'Santo André - SP', null, null, null, 'manual_google', true, 'dedetizadora-lava-imper-santo-andre', 'dedetizadora', null, null),
  (gen_random_uuid(), 'El Shaday Dedetizadora', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Jardim Santo André', 'Rua dos Vicentinos, 0', null, null, null, 'manual_google', true, 'el-shaday-dedetizadora-santo-andre', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Aquatech Dedetizadora', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Jaçatuba', 'Rua Mossoro, 0', null, null, null, 'manual_google', true, 'aquatech-dedetizadora-santo-andre', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Dedetize', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Vila Alzira', 'Rua Paranapanema, 0', null, null, null, 'manual_google', true, 'dedetize-santo-andre', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Abclean Dedetizadora', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Jardim Irene', 'Rua Ramalho Ortigao, 0', null, null, null, 'manual_google', true, 'abclean-dedetizadora-santo-andre', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Isokan Comércio e Serviços', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Jardim Las Vegas', 'Rua Dona Nina Zanotto, 0', null, null, null, 'manual_google', true, 'isokan-comercio-e-servicos-santo-andre', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Alvim Análises', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Vila Assunção', 'Av Joao Ramalho, 0', null, null, null, 'manual_google', true, 'alvim-analises-santo-andre', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Ponto Certo Controle de Pragas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Utinga', 'Rua Dublin, 0', null, null, null, 'manual_google', true, 'ponto-certo-controle-de-pragas-santo-andre', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Sanit Control', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Vila Camilópolis', 'Rua Sud Menucci, 0', null, null, null, 'manual_google', true, 'sanit-control-santo-andre', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Rotor System', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Vila Alzira', 'Rua Paranapanema, 0', null, null, null, 'manual_google', true, 'rotor-system-santo-andre', 'dedetizadora', null, null),
  (gen_random_uuid(), 'No Bugs Controle de Pragas', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Marajoara', 'Rua Benedito Montenegro, 0', null, null, null, 'manual_google', true, 'no-bugs-controle-de-pragas-santo-andre', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Controlar Dedetizadora', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Oratório', 'Rua Oratorio, 0', null, null, null, 'manual_google', true, 'controlar-dedetizadora-santo-andre', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Ecológica Montenegro', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Parque Oratório', 'Rua Montenegro, 0', null, null, null, 'manual_google', true, 'ecologica-montenegro-santo-andre', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Yofel Dedetizadora', (SELECT id FROM public.cities WHERE slug='santo-andre'), 'Vila Pires', 'Av Ibirapitanga, 0', null, null, null, 'manual_google', true, 'yofel-dedetizadora-santo-andre', 'dedetizadora', null, null)
ON CONFLICT (slug) DO NOTHING;
