-- 1. Ensure City Exists (São Caetano do Sul)
INSERT INTO public.cities (name, slug, state)
VALUES ('São Caetano do Sul', 'sao-caetano-do-sul', 'SP')
ON CONFLICT (slug) DO NOTHING;

-- 2. Insert Providers
-- Using gen_random_uuid() for IDs
-- Using subquery for city_id
-- Using ON CONFLICT (slug) DO NOTHING
INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  (gen_random_uuid(), 'Motta Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Rua Santa Paula, 500', '11947230001', '1142241000', 'contato@mottaimoveis.com.br', 'manual_google', true, 'motta-imoveis', 'imobiliaria', 'https://www.mottaimoveis.com.br', 'J-18884'),
  (gen_random_uuid(), 'Guaíra Imóveis - São Caetano', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Avenida Goiás, 1400', '11999990002', '1142239000', 'scs@guairaimoveis.com.br', 'manual_google', true, 'guaira-imoveis-sao-caetano', 'imobiliaria', 'https://www.guairaimoveis.com.br', 'J-16501'),
  (gen_random_uuid(), 'Casari Imóveis SCS', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Rua Visconde de Inhaúma, 450', '11940120003', '1142337000', 'casari@casari.com.br', 'manual_google', true, 'casari-imoveis-scs', 'imobiliaria', 'https://www.casari.com.br', 'J-14532'),
  (gen_random_uuid(), 'Nova Geração Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Centro', 'Rua Manuel Coelho, 676', '11956560004', '1142283000', null, 'manual_google', true, 'nova-geracao-imoveis', 'imobiliaria', 'https://www.novageracaoimoveis.com.br', 'J-21045'),
  (gen_random_uuid(), 'Viana Negócios Imobiliários', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Avenida Goiás, 2033', '11947270005', '1142278000', 'viana@viana.com.br', 'manual_google', true, 'viana-negocios-imobiliarios-scs', 'imobiliaria', 'https://www.viana.com.br', 'J-13654'),
  (gen_random_uuid(), 'Focus Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Maria', 'Alameda Terracota, 215', '11974440006', '1142211515', 'vendas@focusimoveis.com.br', 'manual_google', true, 'focus-imoveis', 'imobiliaria', 'https://www.focusimoveis.com.br', 'J-25678'),
  (gen_random_uuid(), 'A.B. Entringer', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Centro', 'Rua Baraldi, 843', null, '1142216500', null, 'manual_google', true, 'ab-entringer', 'imobiliaria', 'http://www.abentringer.com.br', 'J-4521'),
  (gen_random_uuid(), 'Imobiliária Pinotti', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Olímpico', 'Rua Visconde de Inhaúma, 1050', '11940300008', '1142385555', 'pinotti@pinotti.com.br', 'manual_google', true, 'imobiliaria-pinotti', 'imobiliaria', 'https://www.pinotti.com.br', 'J-11234'),
  (gen_random_uuid(), 'Bonini Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Rua Taipas, 545', '11971710009', '1142273000', 'contato@boniniimoveis.com.br', 'manual_google', true, 'bonini-imoveis', 'imobiliaria', 'https://www.boniniimoveis.com.br', 'J-26330'),
  (gen_random_uuid(), 'Sanches Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Boa Vista', 'Rua Visconde de Inhaúma, 345', '11947210010', '1142338888', null, 'manual_google', true, 'sanches-imoveis', 'imobiliaria', 'https://www.sanchesimoveis.com.br', 'J-19987'),
  (gen_random_uuid(), 'Eduardo Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Rua Maceió, 540', '11940020011', '1142245050', null, 'manual_google', true, 'eduardo-imoveis', 'imobiliaria', 'https://www.eduardoimoveis.com.br', 'J-17741'),
  (gen_random_uuid(), 'Edelson Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Rua Oswaldo Cruz, 955', '11947470012', '1142214444', null, 'manual_google', true, 'edelson-imoveis', 'imobiliaria', 'https://www.edelsonimoveis.com.br', 'J-22331'),
  (gen_random_uuid(), 'Ferreira Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Olímpico', 'Rua Visconde de Inhaúma, 788', '11988880013', '1142321010', null, 'manual_google', true, 'ferreira-imoveis', 'imobiliaria', 'http://www.imobiliariaferreira.com.br', 'J-15555'),
  (gen_random_uuid(), 'Macedo Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Boa Vista', 'Rua Amazonas, 3300', '11945450014', '1142387000', null, 'manual_google', true, 'macedo-imoveis', 'imobiliaria', 'https://www.macedoimoveis.com.br', 'J-28821'),
  (gen_random_uuid(), 'Fenix Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Rua Maranhão, 850', '11999110015', '1142217777', null, 'manual_google', true, 'fenix-imoveis', 'imobiliaria', 'http://www.feniximoveis.com.br', 'J-33442'),
  (gen_random_uuid(), 'Exclusiva Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Centro', 'Avenida Goiás, 601', '11947211616', '1142261000', 'vendas@exclusivasc.com.br', 'manual_google', true, 'exclusiva-imoveis-scs', 'imobiliaria', 'https://www.exclusivasc.com.br', 'J-24410'),
  (gen_random_uuid(), 'Imobiliária Atuante', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Olímpico', 'Rua Visconde de Inhaúma, 950', '11947320017', '1142324400', null, 'manual_google', true, 'imobiliaria-atuante', 'imobiliaria', 'https://www.atuanteimoveis.com.br', 'J-18231'),
  (gen_random_uuid(), 'Thera Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Rua General Osório, 120', '11940141818', '1142212233', null, 'manual_google', true, 'thera-imoveis', 'imobiliaria', 'https://www.theraimoveis.com.br', 'J-29851'),
  (gen_random_uuid(), 'JD Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Rua Alegre, 600', '11999550019', '1142246060', null, 'manual_google', true, 'jd-imoveis', 'imobiliaria', 'https://www.jdimoveis.com.br', 'J-16782'),
  (gen_random_uuid(), 'Pedro de Oliveira Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Centro', 'Rua Baraldi, 900', '11947223020', '1142215000', 'pedro@pedrodeoliveira.com.br', 'manual_google', true, 'pedro-de-oliveira-imoveis', 'imobiliaria', 'https://www.pedrodeoliveira.com.br', 'J-5241'),
  (gen_random_uuid(), 'S.C.S. Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Avenida Goiás, 1800', '11956562121', '1142275555', null, 'manual_google', true, 'scs-imoveis', 'imobiliaria', 'http://www.scsimoveis.com.br', 'J-19911'),
  (gen_random_uuid(), 'Barcelona Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Rua Taipas, 600', '11940122222', '1142247777', null, 'manual_google', true, 'barcelona-imoveis', 'imobiliaria', 'http://www.barcelonaimoveis.com.br', 'J-14567'),
  (gen_random_uuid(), 'Santa Paula Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Rua Santa Paula, 300', '11974742323', '1142213030', null, 'manual_google', true, 'santa-paula-imoveis', 'imobiliaria', 'http://www.santapaulaimoveis.com.br', 'J-21222'),
  (gen_random_uuid(), 'B.X. Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Boa Vista', 'Rua Visconde de Inhaúma, 120', '11988882424', '1142319000', null, 'manual_google', true, 'bx-imoveis', 'imobiliaria', 'http://www.bximoveis.com.br', 'J-30123'),
  (gen_random_uuid(), 'G.P. Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Fundação', 'Rua Mariano Pamplona, 150', '11940022525', '1142291010', null, 'manual_google', true, 'gp-imoveis', 'imobiliaria', 'http://www.gpimoveis.com.br', 'J-27654'),
  (gen_random_uuid(), 'L.G. Imóveis SCS', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Olímpico', 'Avenida Senador Roberto Simonsen, 500', '11947322626', '1142384000', null, 'manual_google', true, 'lg-imoveis-scs', 'imobiliaria', 'http://www.lgimoveis.com.br', 'J-19888'),
  (gen_random_uuid(), 'Prime Imóveis SCS', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Rua Maranhão, 1000', '11940142727', '1142218888', null, 'manual_google', true, 'prime-imoveis-scs', 'imobiliaria', 'https://www.primeimoveis.com.br', 'J-31222'),
  (gen_random_uuid(), 'Vision Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Centro', 'Rua Manuel Coelho, 500', '11956562828', '1142267070', null, 'manual_google', true, 'vision-imoveis', 'imobiliaria', 'http://www.visionimoveis.com.br', 'J-25333'),
  (gen_random_uuid(), 'Ativa Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Maria', 'Rua General Osório, 450', '11940302929', '1142219999', null, 'manual_google', true, 'ativa-imoveis-scs', 'imobiliaria', 'http://www.ativaimoveis.com.br', 'J-20444'),
  (gen_random_uuid(), 'Aliança Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Rua Maceió, 150', '11971713030', '1142248888', null, 'manual_google', true, 'alianca-imoveis', 'imobiliaria', 'http://www.aliancaimoveis.com.br', 'J-15333'),
  (gen_random_uuid(), 'Conquista Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Olímpico', 'Rua Visconde de Inhaúma, 1200', '11947213131', '1142331010', null, 'manual_google', true, 'conquista-imoveis-scs', 'imobiliaria', 'http://www.conquistaimoveis.com.br', 'J-29876'),
  (gen_random_uuid(), 'Elite Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Rua Oswaldo Cruz, 1100', '11940023232', '1142215500', null, 'manual_google', true, 'elite-imoveis-scs', 'imobiliaria', 'http://www.eliteimoveis.com.br', 'J-23111'),
  (gen_random_uuid(), 'Nobre Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Centro', 'Avenida Goiás, 900', '11988883333', '1142264040', null, 'manual_google', true, 'nobre-imoveis', 'imobiliaria', 'http://www.nobreimoveis.com.br', 'J-26777'),
  (gen_random_uuid(), 'Realiza Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Boa Vista', 'Rua Amazonas, 2800', '11999113434', '1142386060', null, 'manual_google', true, 'realiza-imoveis', 'imobiliaria', 'http://www.realizaimoveis.com.br', 'J-18555'),
  (gen_random_uuid(), 'Versátil Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Rua Alegre, 800', '11947213535', '1142241515', null, 'manual_google', true, 'versatil-imoveis', 'imobiliaria', 'http://www.versatilimoveis.com.br', 'J-32111'),
  (gen_random_uuid(), 'Atitude Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Olímpico', 'Avenida Tieppe, 150', '11947323636', '1142327070', null, 'manual_google', true, 'atitude-imoveis-scs', 'imobiliaria', 'http://www.atitudeimoveis.com.br', 'J-28555'),
  (gen_random_uuid(), 'Estilo Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Rua Maranhão, 450', '11940143737', '1142211212', null, 'manual_google', true, 'estilo-imoveis', 'imobiliaria', 'http://www.estiloimoveis.com.br', 'J-21444'),
  (gen_random_uuid(), 'Conceito Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Centro', 'Rua Baraldi, 1100', '11956563838', '1142263030', null, 'manual_google', true, 'conceito-imoveis-scs', 'imobiliaria', 'http://www.conceitoimoveis.com.br', 'J-27333'),
  (gen_random_uuid(), 'Dinâmica Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Boa Vista', 'Rua Visconde de Inhaúma, 1400', '11940303939', '1142381111', null, 'manual_google', true, 'dinamica-imoveis', 'imobiliaria', 'http://www.dinamicaimoveis.com.br', 'J-19666'),
  (gen_random_uuid(), 'Global Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Rua Maceió, 350', '11971714040', '1142242222', null, 'manual_google', true, 'global-imoveis-scs', 'imobiliaria', 'http://www.globalimoveis.com.br', 'J-14777'),
  (gen_random_uuid(), 'Líder Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Rua Oswaldo Cruz, 1500', '11947214141', '1142214040', null, 'manual_google', true, 'lider-imoveis-scs', 'imobiliaria', 'http://www.liderimoveis.com.br', 'J-23444'),
  (gen_random_uuid(), 'Master Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Centro', 'Avenida Goiás, 1200', '11940024242', '1142265050', null, 'manual_google', true, 'master-imoveis-scs', 'imobiliaria', 'http://www.masterimoveis.com.br', 'J-18999'),
  (gen_random_uuid(), 'Padrão Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Boa Vista', 'Rua Amazonas, 3500', '11988884343', '1142382020', null, 'manual_google', true, 'padrao-imoveis-scs', 'imobiliaria', 'http://www.padraoimoveis.com.br', 'J-29333'),
  (gen_random_uuid(), 'Qualidade Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Olímpico', 'Rua Visconde de Inhaúma, 1600', '11999114444', '1142335555', null, 'manual_google', true, 'qualidade-imoveis', 'imobiliaria', 'http://www.qualidadeimoveis.com.br', 'J-21777'),
  (gen_random_uuid(), 'Referência Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Rua Alegre, 1000', '11947214545', '1142249090', null, 'manual_google', true, 'referencia-imoveis', 'imobiliaria', 'http://www.referenciaimoveis.com.br', 'J-15888'),
  (gen_random_uuid(), 'Sucesso Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Paula', 'Rua Maranhão, 1200', '11947324646', '1142216666', null, 'manual_google', true, 'sucesso-imoveis', 'imobiliaria', 'http://www.sucessoimoveis.com.br', 'J-30444'),
  (gen_random_uuid(), 'Valor Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Centro', 'Rua Manuel Coelho, 900', '11940144747', '1142268888', null, 'manual_google', true, 'valor-imoveis', 'imobiliaria', 'http://www.valorimoveis.com.br', 'J-24111'),
  (gen_random_uuid(), 'Vitória Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Boa Vista', 'Rua Amazonas, 4000', '11956564848', '1142384444', null, 'manual_google', true, 'vitoria-imoveis-scs', 'imobiliaria', 'http://www.vitoriaimoveis.com.br', 'J-28111'),
  (gen_random_uuid(), 'Zion Imóveis', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Barcelona', 'Rua Taipas, 1000', '11940304949', '1142243333', null, 'manual_google', true, 'zion-imoveis', 'imobiliaria', 'http://www.zionimoveis.com.br', 'J-33777'),
  (gen_random_uuid(), 'Alpha Imóveis SCS', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'Santa Maria', 'Alameda Terracota, 500', '11971715050', '1142211010', null, 'manual_google', true, 'alpha-imoveis-scs', 'imobiliaria', 'http://www.alphaimoveisscs.com.br', 'J-12111')
ON CONFLICT (slug) DO NOTHING;
