-- 1. Ensure City Exists (São Bernardo do Campo)
INSERT INTO public.cities (name, slug, state)
VALUES ('São Bernardo do Campo', 'sao-bernardo-do-campo', 'SP')
ON CONFLICT (slug) DO NOTHING;

-- 2. Insert Providers (Automotive)
-- Using gen_random_uuid() for IDs to ensure uniqueness if conflicting with other seeds
INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  (gen_random_uuid(), 'Camino Car Multimarcas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'Rua Alferes Bonilha, 579', '11947285145', '1141291063', 'contato@caminocar.com.br', 'manual_google', true, 'camino-car-multimarcas-sbc', 'automoveis', 'https://www.caminocar.com.br', null),
  (gen_random_uuid(), 'MPCar Veículos', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'Av. Brigadeiro Faria Lima, 760', '11947951441', '11947951441', 'mpcar_@hotmail.com', 'manual_google', true, 'mpcar-veiculos-sbc', 'automoveis', 'https://www.mpcarsbc.com.br', null),
  (gen_random_uuid(), 'São Bernardo Automóveis', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'Av. Newton M. de Andrade, 111', '11951247969', '1126697338', 'vendas@saobernardoautomoveis.com.br', 'manual_google', true, 'sao-bernardo-automoveis-sbc', 'automoveis', 'https://www.saobernardoautomoveis.com.br', null),
  (gen_random_uuid(), 'Viamar Chevrolet', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Baeta Neves', 'Av. Pereira Barreto, 1380', '11968665000', '1121006000', 'contato@viamar.com.br', 'manual_google', true, 'viamar-chevrolet-sbc', 'automoveis', 'https://www.viamar.com.br', null),
  (gen_random_uuid(), 'Auto News Multimarcas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'AV BRIGADEIRO FARIA LIMA Nº 658', '1143323222', '1143323222', 'autonewsbc@gmail.com', 'manual_google', true, 'auto-news-multimarcas-sbc', 'automoveis', 'https://www.autonewmultimarcas.com.br', null),
  (gen_random_uuid(), 'Brilho''s Car', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Rudge Ramos', 'Rua Afonsina, 104', '11950395102', '1143651612', 'brilhoscar104@gmail.com', 'manual_google', true, 'brilhos-car-sbc', 'automoveis', 'https://www.brilhoscar.com.br', null),
  (gen_random_uuid(), 'Stock Motors', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Jardim do Mar', 'Avenida Kennedy, 239', '11991631872', '1123565423', 'contato@stockmotorssp.com.br', 'manual_google', true, 'stock-motors-sbc', 'automoveis', 'https://www.stockmotorssp.com.br', null),
  (gen_random_uuid(), 'Edu Automóveis', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'Rua Jurubatuba, 1365', '1141254444', '1141254444', 'contato@eduautomoveis.com.br', 'manual_google', true, 'edu-automoveis-sbc', 'automoveis', 'https://www.eduautomoveis.com.br', null),
  (gen_random_uuid(), 'JS Multimarcas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'Rua Jurubatuba, 945', '1143305000', '1143305000', 'contato@jsmultimarcassbc.com.br', 'manual_google', true, 'js-multimarcas-sbc', 'automoveis', 'https://www.jsmultimarcassbc.com.br', null),
  (gen_random_uuid(), 'ABC Veículos', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'Rua Jurubatuba, 825', '1141255500', '1141255500', 'vendas@abcveiculos.com.br', 'manual_google', true, 'abc-veiculos-sbc', 'automoveis', 'https://www.abcveiculos.com.br', null),
  (gen_random_uuid(), 'CR Car Veículos', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'Rua Jurubatuba, 1049', '1141249999', '1141249999', 'contato@crcarveiculos.com.br', 'manual_google', true, 'cr-car-veiculos-sbc', 'automoveis', 'https://www.crcarveiculos.com.br', null),
  (gen_random_uuid(), 'Nissi Automóveis', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'Rua Jurubatuba, 1650', '1141258888', '1141258888', 'contato@nissiautomoveis.com.br', 'manual_google', true, 'nissi-automoveis-sbc', 'automoveis', 'https://www.nissiautomoveis.com.br', null),
  (gen_random_uuid(), 'Codonho Motors', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'Rua Jurubatuba, 1535', '1141223333', '1141223333', 'vendas@codonhomotors.com.br', 'manual_google', true, 'codonhomotors-sbc', 'automoveis', 'https://www.codonhomotors.com.br', null),
  (gen_random_uuid(), 'Jurubatuba Automóveis', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'Rua Jurubatuba, 2015', '1141235555', '1141235555', 'contato@jurubatubaautomoveis.com.br', 'manual_google', true, 'jurubatuba-automoveis-sbc', 'automoveis', null, null),
  (gen_random_uuid(), 'Shelby Motors', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Rudge Ramos', 'Estrada das Lágrimas, 77 (Auto Shopping Premium)', '1143680000', '1143680000', 'contato@shelbymotors.com.br', 'manual_google', true, 'shelby-motors-sbc', 'automoveis', 'https://www.premiumsaobernardo.com.br', null),
  (gen_random_uuid(), 'Valteo Car Multimarcas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Rudge Ramos', 'Estrada das Lágrimas, 77 (Auto Shopping Premium)', '1143680000', '1143680000', 'contato@valteo.com.br', 'manual_google', true, 'valteo-car-multimarcas-sbc', 'automoveis', 'https://www.premiumsaobernardo.com.br', null),
  (gen_random_uuid(), 'Solus Multimarcas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Rudge Ramos', 'Estrada das Lágrimas, 77 (Auto Shopping Premium)', '1143680000', '1143680000', 'contato@solus.com.br', 'manual_google', true, 'solus-multimarcas-sbc', 'automoveis', 'https://www.premiumsaobernardo.com.br', null),
  (gen_random_uuid(), 'Route Multimarcas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Rudge Ramos', 'Estrada das Lágrimas, 77 (Auto Shopping Premium)', '1143680000', '1143680000', 'contato@route.com.br', 'manual_google', true, 'route-multimarcas-sbc', 'automoveis', 'https://www.premiumsaobernardo.com.br', null),
  (gen_random_uuid(), 'RKR Motors', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Rudge Ramos', 'Estrada das Lágrimas, 77 (Auto Shopping Premium)', '1143680000', '1143680000', 'contato@rkr.com.br', 'manual_google', true, 'rkr-motors-sbc', 'automoveis', 'https://www.premiumsaobernardo.com.br', null),
  (gen_random_uuid(), '2 Mil Multimarcas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Rudge Ramos', 'Estrada das Lágrimas, 77 (Auto Shopping Premium)', '1143680000', '1143680000', 'contato@2mil.com.br', 'manual_google', true, '2-mil-multimarcas-sbc', 'automoveis', 'https://www.premiumsaobernardo.com.br', null),
  (gen_random_uuid(), 'Brumer Multimarcas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Rudge Ramos', 'Estrada das Lágrimas, 77 (Auto Shopping Premium)', '1143680000', '1143680000', 'contato@brumer.com.br', 'manual_google', true, 'brumer-multimarcas-sbc', 'automoveis', 'https://www.premiumsaobernardo.com.br', null),
  (gen_random_uuid(), 'Rod Car Multimarcas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Rudge Ramos', 'Estrada das Lágrimas, 77 (Auto Shopping Premium)', '1143680000', '1143680000', 'contato@rodcar.com.br', 'manual_google', true, 'rod-car-multimarcas-sbc', 'automoveis', 'https://www.premiumsaobernardo.com.br', null),
  (gen_random_uuid(), 'Celcar Multimarcas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Rudge Ramos', 'Estrada das Lágrimas, 77 (Auto Shopping Premium)', '1143680000', '1143680000', 'contato@celcar.com.br', 'manual_google', true, 'celcar-multimarcas-sbc', 'automoveis', 'https://www.premiumsaobernardo.com.br', null),
  (gen_random_uuid(), 'Lion Seminovos', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Taboão', 'Av. Taboão, 455 (Auto Shopping Anchieta)', '1147700588', '1147700588', 'contato@lionseminovos.com.br', 'manual_google', true, 'lion-seminovos-sbc', 'automoveis', 'https://www.autoshoppinganchieta.com', null),
  (gen_random_uuid(), 'D Queiroz', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Taboão', 'Av. Taboão, 455 (Auto Shopping Anchieta)', '1147700588', '1147700588', 'contato@dqueiroz.com.br', 'manual_google', true, 'd-queiroz-sbc', 'automoveis', 'https://www.autoshoppinganchieta.com', null),
  (gen_random_uuid(), 'Insta Shopping', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Taboão', 'Av. Taboão, 455 (Auto Shopping Anchieta)', '1147700588', '1147700588', 'contato@instashopping.com.br', 'manual_google', true, 'insta-shopping-sbc', 'automoveis', 'https://www.autoshoppinganchieta.com', null),
  (gen_random_uuid(), 'Gilcar Veículos', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Rudge Ramos', 'Av. Senador Vergueiro, 4000', '1143621500', '1143621500', 'contato@gilcar.com.br', 'manual_google', true, 'gilcar-veiculos-sbc', 'automoveis', 'https://www.gilcar.com.br', null),
  (gen_random_uuid(), 'Vitória Veículos', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'Rua Jurubatuba, 700', '1141225000', '1141225000', 'contato@vitoriaveiculos.com.br', 'manual_google', true, 'vitoria-veiculos-sbc', 'automoveis', 'https://www.vitoriaveiculossbc.com.br', null),
  (gen_random_uuid(), 'Américo Veículos', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'Av. Francisco Prestes Maia, 850', '1141257777', '1141257777', 'contato@americoveiculos.com.br', 'manual_google', true, 'americo-veiculos-sbc', 'automoveis', null, null),
  (gen_random_uuid(), 'Ricardinho Automóveis', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'Rua Jurubatuba, 1100', '1141258800', '1141258800', 'contato@ricardinhoautomoveis.com.br', 'manual_google', true, 'ricardinho-automoveis-sbc', 'automoveis', null, null)
ON CONFLICT (slug) DO NOTHING;
