-- 1. Ensure City Exists (Mauá)
INSERT INTO public.cities (name, slug, state)
VALUES ('Mauá', 'maua', 'SP')
ON CONFLICT (slug) DO NOTHING;

-- 2. Insert Providers (Automotive)
-- Using gen_random_uuid() for IDs
INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  (gen_random_uuid(), 'Chevrolet Vigorito Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Noemia', 'Av. Papa João XXIII, 677', '1145428000', '1145428000', 'contato@vigoritogm.com.br', 'manual_google', true, 'chevrolet-vigorito-maua', 'automoveis', 'https://www.vigoritogm.com.br', null),
  (gen_random_uuid(), 'Renault Armando Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Parque São Vicente', 'Av. João Ramalho, 1655', '1127616600', '1127616600', 'contato@armandorenault.com.br', 'manual_google', true, 'renault-armando-maua', 'automoveis', 'https://www.armandorenault.com.br', null),
  (gen_random_uuid(), 'Toyota Savol Mauá', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Noemia', 'Av. João Ramalho, 1853', '1149796000', '1149796000', 'contato@savoltoyota.com.br', 'manual_google', true, 'toyota-savol-maua', 'automoveis', 'https://www.savoltoyota.com.br', null),
  (gen_random_uuid(), 'Volkswagen Vigo Motors', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Av. Papa João XXIII, 677', '1145124012', '1145124012', 'contato@vigomotors.com.br', 'manual_google', true, 'volkswagen-vigo-motors-maua', 'automoveis', 'https://www.vigomotors.com.br', null),
  (gen_random_uuid(), 'Canaã Multimarcas', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila America', 'Av. Barão de Mauá, 1779', '1145162030', '1145162030', 'canaamultimarcas19@gmail.com', 'manual_google', true, 'canaa-multimarcas-maua', 'automoveis', 'https://www.canaamultimarcas.com.br', null),
  (gen_random_uuid(), 'D''Queiroz Multimarcas', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila América', 'Avenida Barão de Mauá, 1540', '11992243849', '11992243849', 'dqueirozmultimarcas@hotmail.com', 'manual_google', true, 'd-queiroz-multimarcas-maua', 'automoveis', 'https://www.dqueirozmultimarcas.com.br', null),
  (gen_random_uuid(), 'Léo Multimarcas', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Guarani', 'Rua Luís Bernardi, 58', '11976049998', '11976049998', 'contato@leomultimarcas.com.br', 'manual_google', true, 'leo-multimarcas-maua', 'automoveis', null, null),
  (gen_random_uuid(), 'Moriah Multimarcas', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Bocaina', 'Rua Almirante Tamandaré, 450', '1145196000', '1145196000', 'contato@moriahmultimarcas.com.br', 'manual_google', true, 'moriah-multimarcas-maua', 'automoveis', 'https://www.moriahmultimarcas.com.br', null),
  (gen_random_uuid(), 'Prata Car Multimarcas', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Noêmia', 'Av. João Ramalho, 1745', '1135931510', '1135931510', 'contato@pratacarmultimarcas.com', 'manual_google', true, 'prata-car-multimarcas-maua', 'automoveis', 'https://www.pratacarmultimarcas.com', null),
  (gen_random_uuid(), 'Space Multicar Veículos', (SELECT id FROM public.cities WHERE slug='maua'), 'Jardim Mauá', 'Av. Barão de Mauá, 2828', '1145551234', '1145551234', 'contato@spacemulticar.com.br', 'manual_google', true, 'space-multicar-veiculos-maua', 'automoveis', 'https://www.spacemulticarveiculos.com.br', null),
  (gen_random_uuid(), 'T & G Multimarcas', (SELECT id FROM public.cities WHERE slug='maua'), 'Jd. Maringá', 'Av. Barão de Mauá, 3934', '11915710712', '1144786254', 'dimasconsultor@outlook.com', 'manual_google', true, 'tg-multimarcas-maua', 'automoveis', 'https://www.tegmultimarcas.com.br', null),
  (gen_random_uuid(), 'Vitor Multimarcas', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Assis Brasil', 'R. Lazar Segall, 60', '1145555519', '1145555519', 'vitormultimarcasveiculos@gmail.com', 'manual_google', true, 'vitor-multimarcas-maua', 'automoveis', 'https://www.vitormultimarcasveiculos.com.br', null),
  (gen_random_uuid(), 'Auto Shopping Veículos', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Bocaina', 'Rua General Osório, 222', '1145155000', '1145155000', 'contato@autoshoppingveiculos.com.br', 'manual_google', true, 'auto-shopping-veiculos-maua', 'automoveis', null, null),
  (gen_random_uuid(), 'Barão Automóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Noêmia', 'Avenida Papa João XXIII, 555', '1145142000', '1145142000', 'contato@baraoautomoveis.com.br', 'manual_google', true, 'barao-automoveis-maua', 'automoveis', null, null),
  (gen_random_uuid(), 'Bacchi Veículos', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Guarani', 'Rua Rio Branco, 460', '1145551000', '1145551000', 'contato@bacchiveiculos.com.br', 'manual_google', true, 'bacchi-veiculos-maua', 'automoveis', null, null),
  (gen_random_uuid(), 'Caballero Multimarcas', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Bocaina', 'Rua dos Bandeirantes, 300', '1145136000', '1145136000', 'contato@caballero.com.br', 'manual_google', true, 'caballero-multimarcas-maua', 'automoveis', null, null),
  (gen_random_uuid(), 'CB Autos Seminovos', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Vitória', 'Avenida Antonia Rosa Fioravanti, 1300', '1145129000', '1145129000', 'contato@cbautos.com.br', 'manual_google', true, 'cb-autos-seminovos-maua', 'automoveis', null, null),
  (gen_random_uuid(), 'Coalhauto Veículos', (SELECT id FROM public.cities WHERE slug='maua'), 'Parque São Vicente', 'Avenida João Ramalho, 2050', '1145559999', '1145559999', 'contato@coalhauto.com.br', 'manual_google', true, 'coalhauto-veiculos-maua', 'automoveis', null, null),
  (gen_random_uuid(), 'D''Angelos Veículos', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Assis', 'Rua Dom José Gaspar, 800', '1145112233', '1145112233', 'contato@dangelos.com.br', 'manual_google', true, 'dangelos-veiculos-maua', 'automoveis', null, null),
  (gen_random_uuid(), 'EcoAra Veículos', (SELECT id FROM public.cities WHERE slug='maua'), 'Jardim Araguaia', 'Rua das Camélias, 120', '1145148000', '1145148000', 'contato@ecoara.com.br', 'manual_google', true, 'ecoara-veiculos-maua', 'automoveis', null, null),
  (gen_random_uuid(), 'Gileno Multimarcas', (SELECT id FROM public.cities WHERE slug='maua'), 'Parque das Américas', 'Rua Havana, 350', '1145447000', '1145447000', 'contato@gileno.com.br', 'manual_google', true, 'gileno-multimarcas-maua', 'automoveis', null, null),
  (gen_random_uuid(), 'Go Semi Novos', (SELECT id FROM public.cities WHERE slug='maua'), 'Centro', 'Av. Gov. Mário Covas Júnior, 2100', '1145125555', '1145125555', 'contato@goseminovos.com.br', 'manual_google', true, 'go-semi-novos-maua', 'automoveis', null, null),
  (gen_random_uuid(), 'Intactus Veículos', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Falchi', 'Rua do Comércio, 50', '1145167777', '1145167777', 'contato@intactus.com.br', 'manual_google', true, 'intactus-veiculos-maua', 'automoveis', null, null),
  (gen_random_uuid(), 'JLN Multimarcas', (SELECT id FROM public.cities WHERE slug='maua'), 'Jardim Zaíra', 'Av. Pres. Castelo Branco, 1500', '1145188888', '1145188888', 'contato@jln.com.br', 'manual_google', true, 'jln-multimarcas-maua', 'automoveis', null, null),
  (gen_random_uuid(), 'Juninho Automóveis', (SELECT id FROM public.cities WHERE slug='maua'), 'Vila Magini', 'Rua Rio de Janeiro, 100', '1145199999', '1145199999', 'contato@juninhoautomoveis.com.br', 'manual_google', true, 'juninho-automoveis-maua', 'automoveis', null, null)
ON CONFLICT (slug) DO NOTHING;
