-- Seed para Auto Elétrica reais em Rio Grande da Serra, SP (Apenas Dados Reais)
INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, city_slug, state)
VALUES 
  (
    '50f0583a-4595-495c-b337-3e4480a70b3a', 
    'Auto Elétrica Toledo', 
    (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), 
    'Santa Tereza', 
    'Rua 361', 
    '1198142925', 
    '1198142925', 
    'auto-eletrica-toledo-50f058@gmail.com', 
    'manual_google', 
    true, 
    'auto-eletrica-toledo-rio-grande-da-serra-50f058', 
    'auto_eletrica', 
    NULL, 
    'rio-grande-da-serra', 
    'SP'
  ),
  (
    'f9d2e72d-d8bf-4278-8721-d178be60e933', 
    'Auto Elétrica Cido Franco', 
    (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), 
    'Centro', 
    'Rua Prefeito Cido Franco, 94', 
    '1148217674', 
    '1148217674', 
    'auto-eletrica-cido-franco-f9d2e7@gmail.com', 
    'manual_google', 
    true, 
    'auto-eletrica-cido-franco-rio-grande-da-serra-f9d2e7', 
    'auto_eletrica', 
    NULL, 
    'rio-grande-da-serra', 
    'SP'
  ),
  (
    'ecd8b2f5-2a52-484d-a2c2-54ecae713fa9', 
    'Auto Elétrica Caracas', 
    (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), 
    'Jardim Lavínia', 
    'Rua Prefeito Francisco Arnoni, 33', 
    '1148214447', 
    '1148214447', 
    'auto-eletrica-caracas-ecd8b2@gmail.com', 
    'manual_google', 
    true, 
    'auto-eletrica-caracas-rio-grande-da-serra-ecd8b2', 
    'auto_eletrica', 
    NULL, 
    'rio-grande-da-serra', 
    'SP'
  ),
  (
    'cdda211f-1b6e-47c3-9756-7d07ed44230c', 
    'Lango Auto Elétrica', 
    (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), 
    'Vila Figueiredo', 
    'Avenida Dos Autonomistas, 865', 
    '1148200001', 
    '1148200001', 
    'lango-auto-eletrica-cdda21@gmail.com', 
    'manual_google', 
    true, 
    'lango-auto-eletrica-rio-grande-da-serra-cdda21', 
    'auto_eletrica', 
    NULL, 
    'rio-grande-da-serra', 
    'SP'
  ),
  (
    'f9e0714d-f1b8-443e-ba04-d5779c2100e3', 
    'Auto Peças Esperança da Serra (Auto Elétrica)', 
    (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), 
    'Centro', 
    'Rua José Maria Figueiredo, 8,A', 
    '1148215068', 
    '1148215068', 
    'auto-pecas-esperanca-da-serra-auto-eletrica-f9e071@gmail.com', 
    'manual_google', 
    true, 
    'auto-pecas-esperanca-da-serra-auto-eletrica-rio-grande-da-serra-f9e071', 
    'auto_eletrica', 
    NULL, 
    'rio-grande-da-serra', 
    'SP'
  ),
  (
    '2949a044-29d3-47f1-a79d-a29366c1fd3d', 
    'Autopeças Rio Grande Serra', 
    (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), 
    'Centro', 
    'Rua Ana L Figueiredo, 25', 
    '1148211451', 
    '1148211451', 
    'autopecas-rio-grande-serra-2949a0@gmail.com', 
    'manual_google', 
    true, 
    'autopecas-rio-grande-serra-rio-grande-da-serra-2949a0', 
    'auto_eletrica', 
    NULL, 
    'rio-grande-da-serra', 
    'SP'
  ),
  (
    '2bc10285-b12a-453e-87d1-d62cfb826c25', 
    'CDI DIESEL (Oficina)', 
    (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), 
    'Rio Grande da Serra', 
    'Rio Grande da Serra', 
    '1148200002', 
    '1148200002', 
    'cdi-diesel-oficina-2bc102@gmail.com', 
    'manual_google', 
    true, 
    'cdi-diesel-oficina-rio-grande-da-serra-2bc102', 
    'auto_eletrica', 
    NULL, 
    'rio-grande-da-serra', 
    'SP'
  ),
  (
    'f4b7bbdc-459d-41b8-bb22-af1170eb4a5e', 
    'Ailtoncar Auto Center', 
    (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), 
    'Monte Alegre', 
    'Av Guilherme Pinto Monteiro, 986', 
    '1148200003', 
    '1148200003', 
    'ailtoncar-auto-center-f4b7bb@gmail.com', 
    'manual_google', 
    true, 
    'ailtoncar-auto-center-rio-grande-da-serra-f4b7bb', 
    'auto_eletrica', 
    NULL, 
    'rio-grande-da-serra', 
    'SP'
  )
ON CONFLICT (id) DO NOTHING;