-- Script para limpar Lojas de Veículos que caíram acidentalmente na categoria Mecânica (ou outras)
CREATE TEMP TABLE bad_providers AS
SELECT id FROM public.providers 
WHERE category != 'automoveis' 
  AND name IN (
    'Moove Veículos',
    'Davema Multimarcas',
    'Vigorito Chevrolet',
    'Fiat Savol',
    'Hyundai Caoa',
    'Honda André Ribeiro',
    'Jeep Destaque',
    'Kia Savol',
    'Nissan Armando',
    'Citroën Montparnasse',
    'Chery D21 Motors',
    'Autobim Multimarcas',
    'Via Certa Multimarcas',
    'Fênice Multimarcas',
    'Dom Multimarcas',
    'Century Automóveis',
    'Santo André Automóveis',
    'Renault Santo André',
    'Alpha Motors',
    'Arizona Motors',
    'Auto Fluxo',
    'Automaz Multimarcas',
    'Blascar Multimarcas',
    'Boxter Multimarcas',
    'Canaã ABC Automóveis',
    'Carmax Autos',
    'Cesco Car Multimarcas',
    'Davanti Multimarcas',
    'Evoluir Veículos',
    'Felisa Multimarcas',
    'Front Motors',
    'Garage Cars',
    'Giba Multimarcas',
    'Global Car Store',
    'Grupo Polerá',
    'HR Premium',
    'Quality Multimarcas',
    'Zero Berto Car',
    'Nevada Multimarcas',
    'Carrera Acelera Veículos',
    'Camino Car Multimarcas',
    'MPCar Veículos',
    'São Bernardo Automóveis',
    'Viamar Chevrolet',
    'Auto News Multimarcas',
    'Brilho',
    'Stock Motors',
    'Edu Automóveis',
    'JS Multimarcas',
    'ABC Veículos',
    'CR Car Veículos',
    'Nissi Automóveis',
    'Codonho Motors',
    'Jurubatuba Automóveis',
    'Shelby Motors',
    'Valteo Car Multimarcas',
    'Solus Multimarcas',
    'Route Multimarcas',
    'RKR Motors',
    '2 Mil Multimarcas',
    'Brumer Multimarcas',
    'Rod Car Multimarcas',
    'Celcar Multimarcas',
    'Lion Seminovos',
    'D Queiroz',
    'Insta Shopping',
    'Gilcar Veículos',
    'Vitória Veículos',
    'Américo Veículos',
    'Ricardinho Automóveis',
    'São Caetano Automóveis',
    'Theoria Veículos',
    'Chevrolet Primarca',
    'Ford Mix',
    'Honda Mix',
    'Renault Armando',
    'Toyota Tsusho',
    'Volkswagen Diauto',
    'Scuderia Veículos',
    '355 Automóveis',
    'Cavalcante Veículos',
    'Auto Giros Motors',
    'Abc Autos',
    'Dirvel Veículos',
    'Ferreira Automóveis',
    'Alpha Multimarcas',
    'Sunny Multimarcas',
    'Globo Car 99',
    'Lavo Tour Motors',
    'Canever Veículos',
    'Pistarell Automóveis',
    'Chevrolet Vigorito Mauá',
    'Renault Armando Mauá',
    'Toyota Savol Mauá',
    'Volkswagen Vigo Motors',
    'Canaã Multimarcas',
    'D',
    'Léo Multimarcas',
    'Moriah Multimarcas',
    'Prata Car Multimarcas',
    'Space Multicar Veículos',
    'T & G Multimarcas',
    'Vitor Multimarcas',
    'Auto Shopping Veículos',
    'Barão Automóveis',
    'Bacchi Veículos',
    'Caballero Multimarcas',
    'CB Autos Seminovos',
    'Coalhauto Veículos',
    'EcoAra Veículos',
    'Gileno Multimarcas',
    'Go Semi Novos',
    'Intactus Veículos',
    'JLN Multimarcas',
    'Juninho Automóveis',
    'Chevrolet Viamar Diadema',
    'Renault Armando Diadema',
    'Hyundai Sinal Diadema',
    'OutletKar Diadema',
    'Orense Veículos',
    '21 Veículos',
    'Action Veículos',
    'Alda Veículos',
    'Diadel Veículos',
    'Mavicar Automóveis',
    'Vila Nogueira Multimarcas',
    'Eldorado Veículos',
    'FokoCar',
    'Auto Piraporinha',
    'DiadCar Veículos',
    'Lamarq Veículos',
    'Via Brasil Automóveis',
    'CS Motors',
    'Capitão Multimarcas',
    'Mauro Veículos',
    'OfferCar',
    'Adm Car',
    'Panorama Veículos',
    'Simões Veículos',
    'Caricar Veículos',
    'Iva Car Multimarcas',
    'Realiza Veículos',
    'Ideal Multimarcas'
  );

DELETE FROM public.messages 
WHERE conversation_id IN (
  SELECT id FROM public.conversations 
  WHERE provider_id IN (SELECT id FROM bad_providers)
);

DELETE FROM public.conversations
WHERE provider_id IN (SELECT id FROM bad_providers);

DELETE FROM public.contact_events
WHERE provider_id IN (SELECT id FROM bad_providers);

DELETE FROM public.providers 
WHERE id IN (SELECT id FROM bad_providers);

DROP TABLE bad_providers;
