-- 290_real_imobiliaria_rgs.sql
-- IMOBILIÁRIAS — Rio Grande da Serra
-- Fonte: Pesquisa manual Google/Maps (encontrasp.com.br, sites oficiais)
-- Total: 6 registros

INSERT INTO public.providers (
  id, name, type, city_id, category_id, neighborhood, address,
  whatsapp, phone, email, source, active, created_at, slug,
  category, website, city_slug, state, creci
) VALUES
(
  gen_random_uuid(),
  'Vanderlei Guerra Imóveis',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Prefeito Carlos José Carlson, 249',
  '11974378234',
  '1148202383',
  null,
  'manual_google',
  true,
  now(),
  'vanderlei-guerra-imoveis-rio-grande-da-serra',
  'imobiliaria',
  'https://vanderleiguerraimoveis.com.br',
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Imobiliária São Vicente',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Prefeito Carlos José Carlson, 226',
  '11947470831',
  '1148201334',
  null,
  'manual_google',
  true,
  now(),
  'imobiliaria-sao-vicente-rio-grande-da-serra',
  'imobiliaria',
  'https://saovicenteimobiliaria.com.br',
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Imobiliária Batista',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Prefeito Carlos José Carlson, 100',
  null,
  '1148201512',
  null,
  'manual_google',
  true,
  now(),
  'imobiliaria-batista-rio-grande-da-serra',
  'imobiliaria',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Rodrigues Imóveis',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Avenida Dom Pedro I, 538',
  null,
  '1148201537',
  null,
  'manual_google',
  true,
  now(),
  'rodrigues-imoveis-rio-grande-da-serra',
  'imobiliaria',
  'https://rodriguesimoveis.online',
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Imobiliária JL',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua José Maria de Figueiredo, 229',
  '11998228363',
  '1148214395',
  null,
  'manual_google',
  true,
  now(),
  'imobiliaria-jl-rio-grande-da-serra',
  'imobiliaria',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Mito Empreendimentos Comerciais e Imobiliários',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Estrada Oeste, 14',
  null,
  '1148211788',
  null,
  'manual_google',
  true,
  now(),
  'mito-empreendimentos-rio-grande-da-serra',
  'imobiliaria',
  null,
  'rio-grande-da-serra',
  'SP',
  null
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_id = EXCLUDED.city_id,
  active = EXCLUDED.active;
