-- 291_real_pedreiro_rgs.sql
-- PEDREIROS / REFORMAS — Rio Grande da Serra
-- Fonte: Pesquisa manual Google/Maps (encontrasp.com.br, guiafacil.com)
-- Total: 5 registros

INSERT INTO public.providers (
  id, name, type, city_id, category_id, neighborhood, address,
  whatsapp, phone, email, source, active, created_at, slug,
  category, website, city_slug, state, creci
) VALUES
(
  gen_random_uuid(),
  'R L Revestimentos e Construções',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Venâncio Orsini, 112',
  null,
  '1148201011',
  null,
  'manual_google',
  true,
  now(),
  'rl-revestimentos-construcoes-rio-grande-da-serra',
  'pedreiro',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'E L O - Construções e Incorporações',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Prefeito Cido Franco, 143',
  null,
  '1148253048',
  null,
  'manual_google',
  true,
  now(),
  'elo-construcoes-incorporacoes-rio-grande-da-serra',
  'pedreiro',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Facilcon Comércio Construções e Serviços',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Prefeito Cido Franco, 214',
  null,
  '1148211001',
  null,
  'manual_google',
  true,
  now(),
  'facilcon-comercio-construcoes-rio-grande-da-serra',
  'pedreiro',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Nilton de Paula Gestor em Negócios Imobiliários e Reformas',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Prefeito Carlos José Carlson, 226',
  '11994206440',
  null,
  null,
  'manual_google',
  true,
  now(),
  'nilton-de-paula-reformas-rio-grande-da-serra',
  'pedreiro',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'CN Serviços Elétricos e Reformas',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Rio Grande da Serra',
  'Rio Grande da Serra - SP',
  '11969397204',
  '11969397204',
  null,
  'manual_google',
  true,
  now(),
  'cn-servicos-reformas-rio-grande-da-serra',
  'pedreiro',
  'https://cnservicoseletricos.com.br',
  'rio-grande-da-serra',
  'SP',
  null
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_id = EXCLUDED.city_id,
  active = EXCLUDED.active;
