-- 299_real_automoveis_rgs.sql
-- LOJAS DE CARROS (AUTOMÓVEIS) — Rio Grande da Serra
-- Fonte: Pesquisa manual Google Maps (verificado via browser)
-- Total: 7 registros
-- Obs: O arquivo 280_automoveis_all.sql não tinha nenhuma entrada para RGS.
--       Todas estas lojas foram verificadas no Google Maps.

INSERT INTO public.providers (
  id, name, type, city_id, category_id, neighborhood, address,
  whatsapp, phone, email, source, active, created_at, slug,
  category, website, city_slug, state, creci
) VALUES
(
  gen_random_uuid(),
  'Pontes Veículos',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Prefeito Cido Franco, 170',
  '11947700817',
  '1148215728',
  null,
  'manual_google',
  true,
  now(),
  'pontes-veiculos-rio-grande-da-serra',
  'automoveis',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'MF Automóveis',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Prefeito Cido Franco, 170',
  null,
  '1148214232',
  null,
  'manual_google',
  true,
  now(),
  'mf-automoveis-rio-grande-da-serra',
  'automoveis',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Danicar Multimarcas',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua José Maria Figueiredo, 236',
  null,
  '1148204298',
  null,
  'manual_google',
  true,
  now(),
  'danicar-multimarcas-rio-grande-da-serra',
  'automoveis',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Pontes Veículos II',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua José Maria Figueiredo, 58',
  '11989744807',
  '11989744807',
  null,
  'manual_google',
  true,
  now(),
  'pontes-veiculos-ii-rio-grande-da-serra',
  'automoveis',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Quallicar Veículos',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Venâncio Orsini, 22',
  '11984382902',
  '11949665152',
  null,
  'manual_google',
  true,
  now(),
  'quallicar-veiculos-rio-grande-da-serra',
  'automoveis',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'PlanAuto Multimarcas',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Av. Dom Pedro I, 780',
  null,
  '1148202669',
  null,
  'manual_google',
  true,
  now(),
  'planauto-multimarcas-rio-grande-da-serra',
  'automoveis',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Juliana Veículos',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Carolina Gomes de Figueiredo',
  '11975444084',
  '11975444084',
  null,
  'manual_google',
  true,
  now(),
  'juliana-veiculos-rio-grande-da-serra',
  'automoveis',
  null,
  'rio-grande-da-serra',
  'SP',
  null
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_id = EXCLUDED.city_id,
  active = EXCLUDED.active;
