-- 303_real_odontologia_rgs.sql
-- CLÍNICAS E DENTISTAS — Rio Grande da Serra
-- Fonte: Google Maps (verificado via browser) + web search
-- Total: 5 registros

INSERT INTO public.providers (
  id, name, type, city_id, category_id, neighborhood, address,
  whatsapp, phone, email, source, active, created_at, slug,
  category, website, city_slug, state, creci
) VALUES
(
  gen_random_uuid(),
  'Odonto Serra',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Prefeito Cido Franco, 381',
  null,
  '1148212770',
  null,
  'manual_google',
  true,
  now(),
  'odonto-serra-rio-grande-da-serra',
  'odontologia',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Smile Odontologia',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Av. Dom Pedro I, 357',
  null,
  '1148212365',
  null,
  'manual_google',
  true,
  now(),
  'smile-odontologia-rio-grande-da-serra',
  'odontologia',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Sorridents Rio Grande da Serra',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Vila Conde',
  'Av. Dom Pedro I, 305',
  null,
  '1148212384',
  null,
  'manual_google',
  true,
  now(),
  'sorridents-rio-grande-da-serra',
  'odontologia',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Clínica Odontológica Dra. Maria Lúcia de Oliveira',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Parque Indaiá',
  'Rua Prefeito Cido Franco, 304',
  null,
  '1148211717',
  null,
  'manual_google',
  true,
  now(),
  'clinica-dra-maria-lucia-rio-grande-da-serra',
  'odontologia',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Ortodontia Dr. Márcio',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Av. Dom Pedro I, 501',
  null,
  '1148202135',
  null,
  'manual_google',
  true,
  now(),
  'ortodontia-dr-marcio-rio-grande-da-serra',
  'odontologia',
  null,
  'rio-grande-da-serra',
  'SP',
  null
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_id = EXCLUDED.city_id,
  active = EXCLUDED.active;
