-- 305_real_personal_trainer_rgs.sql
-- PERSONAL E ACADEMIAS — Rio Grande da Serra
-- Fonte: Google Maps (verificado via browser) + Wellhub/Fresha
-- Total: 5 registros

INSERT INTO public.providers (
  id, name, type, city_id, category_id, neighborhood, address,
  whatsapp, phone, email, source, active, created_at, slug,
  category, website, city_slug, state, creci
) VALUES
(
  gen_random_uuid(),
  'Academia Fit Stop',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Prefeito Cido Franco, 240',
  null,
  '1148211250',
  null,
  'manual_google',
  true,
  now(),
  'academia-fit-stop-rio-grande-da-serra',
  'personal_trainer',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Bio Sport Academia',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Prefeito Cido Franco, 255',
  '11947479759',
  '11947479759',
  null,
  'manual_google',
  true,
  now(),
  'bio-sport-academia-rio-grande-da-serra',
  'personal_trainer',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Academia Vila Conde',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Vila Conde',
  'Av. José Bello, 638',
  null,
  '1148212321',
  null,
  'manual_google',
  true,
  now(),
  'academia-vila-conde-rio-grande-da-serra',
  'personal_trainer',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Academia Power Shape',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Av. Dom Pedro I, 305',
  '11973956548',
  '11973956548',
  null,
  'manual_google',
  true,
  now(),
  'academia-power-shape-rio-grande-da-serra',
  'personal_trainer',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Academia Fox',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Fernão Dias, 35',
  null,
  '1148211770',
  null,
  'manual_google',
  true,
  now(),
  'academia-fox-rio-grande-da-serra',
  'personal_trainer',
  null,
  'rio-grande-da-serra',
  'SP',
  null
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_id = EXCLUDED.city_id,
  active = EXCLUDED.active;
