-- 306_real_estetica_rgs.sql
-- ESTÉTICA E BELEZA — Rio Grande da Serra
-- Fonte: Google Maps (verificado via browser) + Fresha + listamais.com.br
-- Total: 5 registros

INSERT INTO public.providers (
  id, name, type, city_id, category_id, neighborhood, address,
  whatsapp, phone, email, source, active, created_at, slug,
  category, website, city_slug, state, creci
) VALUES
(
  gen_random_uuid(),
  'Glamour Cabelo e Estética',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Prefeito Carlos José Carlson, 120',
  null,
  '1148215338',
  null,
  'manual_google',
  true,
  now(),
  'glamour-cabelo-estetica-rio-grande-da-serra',
  'estetica',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Espaço Estética e Bem Estar',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Prefeito Cido Franco, 381',
  '11948285688',
  '11948285688',
  null,
  'manual_google',
  true,
  now(),
  'espaco-estetica-bem-estar-rio-grande-da-serra',
  'estetica',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Renata Estética',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua João Ramalho, 22',
  '11974121437',
  '11974121437',
  null,
  'manual_google',
  true,
  now(),
  'renata-estetica-rio-grande-da-serra',
  'estetica',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'D''Palle Estética',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rua Prefeito Cido Franco, 48',
  null,
  '1148212746',
  null,
  'manual_google',
  true,
  now(),
  'dpalle-estetica-rio-grande-da-serra',
  'estetica',
  null,
  'rio-grande-da-serra',
  'SP',
  null
),
(
  gen_random_uuid(),
  'Centro de Estética Daniela Ferreira',
  null,
  (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'),
  null,
  'Centro',
  'Rio Grande da Serra - SP',
  '11975882110',
  '11975882110',
  null,
  'manual_google',
  true,
  now(),
  'centro-estetica-daniela-ferreira-rio-grande-da-serra',
  'estetica',
  null,
  'rio-grande-da-serra',
  'SP',
  null
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_id = EXCLUDED.city_id,
  active = EXCLUDED.active;
