-- 31. Insert Handyman (Marido de Aluguel) Providers (Ribeirão Pires)

INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  (gen_random_uuid(), 'JK Marido de Aluguel', (SELECT id FROM public.cities WHERE slug='ribeirao-pires'), 'Ribeirão Pires', 'Ribeirão Pires/SP', '11988794041', '11988794041', 'contato@guiaribeiraopires.com.br', 'manual_google', true, 'jk-marido-de-aluguel-ribeirao-pires', 'marido_aluguel', 'https://www.guiaribeiraopires.com.br', null),
  (gen_random_uuid(), 'Marido de Aluguel Leandro', (SELECT id FROM public.cities WHERE slug='ribeirao-pires'), 'Ribeirão Pires', 'Ribeirão Pires/SP', null, null, 'contato@guiafix.com.br', 'manual_google', true, 'marido-de-aluguel-leandro-ribeirao-pires', 'marido_aluguel', 'https://www.guiafix.com.br', null),
  (gen_random_uuid(), 'SOS Soluções', (SELECT id FROM public.cities WHERE slug='ribeirao-pires'), 'Ribeirão Pires', 'Ribeirão Pires/SP', '11969456072', '11969456072', 'contato@sosreformasereparos.com.br', 'manual_google', true, 'sos-solucoes-ribeirao-pires', 'marido_aluguel', 'https://www.sosreformasereparos.com.br', null),
  (gen_random_uuid(), 'Gutierrez e Aquino Marido de Aluguel', (SELECT id FROM public.cities WHERE slug='ribeirao-pires'), 'Ribeirão Pires', 'Ribeirão Pires/SP', null, null, 'contato@guiafix.com.br', 'manual_google', true, 'gutierrez-aquino-marido-de-aluguel-ribeirao-pires', 'marido_aluguel', 'https://www.guiafix.com.br', null),
  (gen_random_uuid(), 'Marido de Aluguel ABC (Ribeirão)', (SELECT id FROM public.cities WHERE slug='ribeirao-pires'), 'Ribeirão Pires', 'Ribeirão Pires/SP', '11948931000', null, 'contato@maridodealuguel.adm.br', 'manual_google', true, 'marido-de-aluguel-abc-ribeirao-pires', 'marido_aluguel', 'https://www.maridodealuguel.adm.br', null),
  (gen_random_uuid(), 'Cronoshare - Maridos de Aluguel', (SELECT id FROM public.cities WHERE slug='ribeirao-pires'), 'Ribeirão Pires', 'Ribeirão Pires/SP', null, null, 'contato@cronoshare.com.br', 'manual_google', true, 'cronoshare-maridos-de-aluguel-ribeirao-pires', 'marido_aluguel', 'https://www.cronoshare.com.br', null),
  (gen_random_uuid(), 'GetNinjas - Marido de Aluguel', (SELECT id FROM public.cities WHERE slug='ribeirao-pires'), 'Ribeirão Pires', 'Ribeirão Pires/SP', null, null, 'contato@getninjas.com.br', 'manual_google', true, 'getninjas-marido-de-aluguel-ribeirao-pires', 'marido_aluguel', 'https://www.getninjas.com.br', null)
ON CONFLICT (slug) DO NOTHING;
