-- 32. Insert Handyman (Marido de Aluguel) Providers (Rio Grande da Serra)

INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  (gen_random_uuid(), 'Doutor Resolve', (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), 'Rio Grande da Serra', 'Rio Grande da Serra/SP', null, null, 'contato@doutorresolve.com.br', 'manual_google', true, 'doutor-resolve-rio-grande-da-serra', 'marido_aluguel', 'https://www.doutorresolve.com.br', null),
  (gen_random_uuid(), 'Cronoshare - Marido de Aluguel', (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), 'Rio Grande da Serra', 'Rio Grande da Serra/SP', null, null, 'contato@cronoshare.com.br', 'manual_google', true, 'cronoshare-marido-de-aluguel-rio-grande-da-serra', 'marido_aluguel', 'https://www.cronoshare.com.br', null),
  (gen_random_uuid(), 'Master House', (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), 'Rio Grande da Serra', 'Rio Grande da Serra/SP', null, null, 'contato@masterhousesolucoes.com.br', 'manual_google', true, 'master-house-rio-grande-da-serra', 'marido_aluguel', 'https://www.masterhousesolucoes.com.br', null),
  (gen_random_uuid(), 'StarOfService - Marido de Aluguel', (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), 'Rio Grande da Serra', 'Rio Grande da Serra/SP', null, null, 'contato@starofservice.com.br', 'manual_google', true, 'starofservice-marido-de-aluguel-rio-grande-da-serra', 'marido_aluguel', 'https://www.starofservice.com.br', null),
  (gen_random_uuid(), 'Assistência Litt', (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), 'Rio Grande da Serra', 'Rio Grande da Serra/SP', null, null, 'contato@solucoesereparos.com.br', 'manual_google', true, 'assistencia-litt-rio-grande-da-serra', 'marido_aluguel', 'https://www.solucoesereparos.com.br', null),
  (gen_random_uuid(), 'Marido de Aluguel SP', (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), 'Rio Grande da Serra', 'Rio Grande da Serra/SP', '11978869531', '11978869531', null, 'manual_google', true, 'marido-de-aluguel-sp-rio-grande-da-serra', 'marido_aluguel', 'https://www.socorramemaridodealuguel.com.br', null),
  (gen_random_uuid(), 'SOS Soluções', (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), 'Rio Grande da Serra', 'Rio Grande da Serra/SP', '11969456072', '11969456072', 'contato@sosreformasereparos.com.br', 'manual_google', true, 'sos-solucoes-rio-grande-da-serra', 'marido_aluguel', 'https://www.sosreformasereparos.com.br', null)
ON CONFLICT (slug) DO NOTHING;
