-- 35. Insert Electricians (Eletricista) Providers (São Caetano do Sul)

INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  (gen_random_uuid(), 'Eletricista24hs São Caetano do Sul', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11948082000', '5511948082000', 'contato@eletricista24hs.adm.br', 'manual_google', true, 'eletricista-24hs-sao-caetano', 'eletricista', 'https://www.eletricista24hs.adm.br', null),
  (gen_random_uuid(), 'Eletricista em São Caetano', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11986113565', '11986113565', 'contato@eletricistasaobernardo.com.br', 'manual_google', true, 'eletricista-em-sao-caetano', 'eletricista', 'https://www.eletricistasaobernardo.com.br', null),
  (gen_random_uuid(), 'Eletricista São Caetano Sul (Shopping)', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11948931000', '5511948931000', 'contato@eletricista24hs.srv.br', 'manual_google', true, 'eletricista-sao-caetano-sul-shopping', 'eletricista', 'https://www.eletricista24hs.srv.br', null),
  (gen_random_uuid(), 'Eletricista 24 horas Já', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11982232449', '11982232449', 'contato@eletricista24hsja.com.br', 'manual_google', true, 'eletricista-24-horas-ja-scs', 'eletricista', 'https://www.eletricista24hsja.com.br', null),
  (gen_random_uuid(), 'Eletricista Luz | Residencial 24 horas', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11988840073', '11988840073', 'contato@eletricaa.com.br', 'manual_google', true, 'eletricista-luz-scs', 'eletricista', 'https://www.eletricaa.com.br', null),
  (gen_random_uuid(), 'ElectriKmente', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11983324081', '11983324081', 'contato@electrikmente.com.br', 'manual_google', true, 'electrikmente-scs', 'eletricista', 'https://www.electrikmente.com.br', null),
  (gen_random_uuid(), 'TNA Eletricista', (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), 'São Caetano do Sul', 'São Caetano do Sul/SP', '11948931000', null, 'contato@tnaeletricista.com.br', 'manual_google', true, 'tna-eletricista-scs', 'eletricista', 'https://www.tnaeletricista.com.br', null)
ON CONFLICT (slug) DO NOTHING;
