-- 41. Insert Plumbers (Encanador) Providers (São Bernardo do Campo)

INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  (gen_random_uuid(), 'Encanador 24h Perto de Mim', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo/SP', '11912062131', '11912062131', 'contato@encanadorpertodemim.com', 'manual_google', true, 'encanador-24h-perto-de-mim-sbc', 'encanador', 'https://www.encanadorpertodemim.com', null),
  (gen_random_uuid(), 'Encanador São Bernardo do Campo 24 Horas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Rudge Ramos', 'São Bernardo do Campo/SP', '11982085000', '11982085000', 'contato@encanador.srv.br', 'manual_google', true, 'encanador-sao-bernardo-do-campo-24-horas', 'encanador', 'https://www.encanador.srv.br', null),
  (gen_random_uuid(), 'Encanador em São Bernardo do Campo', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Baeta Neves', 'São Bernardo do Campo/SP', '11948931000', '1141144004', 'contato@hidrojateamento.srv.br', 'manual_google', true, 'encanador-em-sao-bernardo-do-campo', 'encanador', 'https://www.hidrojateamento.srv.br', null),
  (gen_random_uuid(), 'SOS Prestadora de Serviços', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo/SP', '11997414460', '11997414460', 'contato@sosprestadoradeservicos.com.br', 'manual_google', true, 'sos-prestadora-de-servicos-sbc', 'encanador', 'https://www.sosprestadoradeservicos.com.br', null),
  (gen_random_uuid(), 'Encanador São Bernardo do Campo (Srv)', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Jardim do Mar', 'São Bernardo do Campo/SP', '11986154000', '11986154000', 'contato@encanador24horas.srv.br', 'manual_google', true, 'encanador-sao-bernardo-do-campo-srv', 'encanador', 'https://www.encanador24horas.srv.br', null),
  (gen_random_uuid(), 'Semsil Encanador 24 Horas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Demarchi', 'São Bernardo do Campo/SP', '11972644553', '1142350534', 'contato@tudoincasa.com.br', 'manual_google', true, 'semsil-encanador-24-horas-sbc', 'encanador', 'https://www.tudoincasa.com.br', null),
  (gen_random_uuid(), 'Encanador em São Bernardo 24hs (Manutenções Rápidas)', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Assunção', 'São Bernardo do Campo/SP', '11966601567', '11966601567', 'contato@manutencoesrapidas.com.br', 'manual_google', true, 'encanador-em-sao-bernardo-24hs-manutencoes', 'encanador', 'https://www.manutencoesrapidas.com.br', null)
ON CONFLICT (slug) DO NOTHING;
