-- Seed: Mentorias de Carreira/Tecnologia - ABC Paulista
-- Cidades: Santo André, São Bernardo, São Caetano, Diadema, Mauá, Ribeirão Pires, Rio Grande da Serra

INSERT INTO public.providers (
  id, name, type, city_id, category_id, neighborhood, address, whatsapp, phone, email, source, active, created_at, slug, category, website, city_slug, state, creci
) VALUES
(gen_random_uuid(), 'Febracis Coaching - Santo André', null, (SELECT id FROM public.cities WHERE slug='santo-andre'), null, 'Bairro Jardim', 'Rua das Figueiras, 1145', '11940053155', '1121991600', 'santoandre@febracis.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'febracis-coaching-santo-andre', 'mentorias_carreira', 'https://febracis.com.br', 'santo-andre', 'SP', null),
(gen_random_uuid(), 'ACISA - Mentoria e NJE', null, (SELECT id FROM public.cities WHERE slug='santo-andre'), null, 'Centro', 'Avenida XV de Novembro, 442', '1121991620', '1121991600', 'falecom@acisa.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'acisa-santo-andre-mentoria', 'mentorias_carreira', 'https://acisa.com.br', 'santo-andre', 'SP', null),
(gen_random_uuid(), 'Mentoris Consultoria e Alavancagem', null, (SELECT id FROM public.cities WHERE slug='santo-andre'), null, 'Centro', 'Rua Bernardino de Campos, 155', '11940272691', '11940272691', 'contato@mentorisconsultoria.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'mentoris-consultoria-santo-andre', 'mentorias_carreira', 'http://mentorisconsultoria.com.br', 'santo-andre', 'SP', null),
(gen_random_uuid(), 'ACISBEC - Mentoria Projetando o Futuro', null, (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), null, 'Centro', 'Rua do Imperador, 14', '11976652257', '1121314800', 'acisbec@acisbec.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'acisbec-sbc-mentoria', 'mentorias_carreira', 'https://acisbec.com.br', 'sao-bernardo-do-campo', 'SP', null),
(gen_random_uuid(), 'Gestaum Lab - Inovação e Mentoria', null, (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), null, 'Anchieta', 'Rua José Versolato, 111', '11987471608', '11987471608', 'contato@gestaumlab.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'gestaum-lab-sbc', 'mentorias_carreira', 'http://gestaumlab.com.br', 'sao-bernardo-do-campo', 'SP', null),
(gen_random_uuid(), 'Simone Ávila Mentoria e Coaching', null, (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), null, 'Santa Paula', 'Rua General Osório, 145', '11999698489', '11999698489', 'contato@simoneavila.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'simone-avila-scs-mentoria', 'mentorias_carreira', 'http://simoneavila.com.br', 'sao-caetano-do-sul', 'SP', null),
(gen_random_uuid(), 'DePraxe RH - Orientação e Carreira', null, (SELECT id FROM public.cities WHERE slug='diadema'), null, 'Centro', 'Rua das Turmalinas, 34', '11962751837', '11962751837', 'depraxerh@gmail.com', 'manual_google', true, '2026-03-06T12:00:00', 'depraxe-rh-diadema', 'mentorias_carreira', 'http://depraxerh.com.br', 'diadema', 'SP', null),
(gen_random_uuid(), 'SODIPROM - Orientação Profissional', null, (SELECT id FROM public.cities WHERE slug='diadema'), null, 'Centro', 'Rua Oriente Monti, 131', '11918478156', '1140541727', 'sodiprom@sodiprom.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'sodiprom-diadema', 'mentorias_carreira', 'http://sodiprom.com.br', 'diadema', 'SP', null),
(gen_random_uuid(), 'Qualifica Mauá - Mentoria de Carreira', null, (SELECT id FROM public.cities WHERE slug='maua'), null, 'Matriz', 'Rua Jundiaí, 63', '11920023429', '11920023429', 'qualifica@maua.sp.gov.br', 'manual_google', true, '2026-03-06T12:00:00', 'qualifica-maua-mentoria', 'mentorias_carreira', 'https://maua.sp.gov.br', 'maua', 'SP', null),
(gen_random_uuid(), 'Epicus Consultoria e Mentoria', null, (SELECT id FROM public.cities WHERE slug='ribeirao-pires'), null, 'Centro', 'Avenida Fortuna, 98', '11943374508', '11943374508', 'contato@epicus.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'epicus-consultoria-ribeirao-pires', 'mentorias_carreira', 'http://epicusconsultoria.com.br', 'ribeirao-pires', 'SP', null),
(gen_random_uuid(), 'Polo & Paula Assessoria e Mentoria', null, (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), null, 'Centro', 'Rua Lidia Pollone, 18', '1148201307', '1148201307', 'contato@poloepaula.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'polo-paula-rgs-assessoria', 'mentorias_carreira', 'http://poloepaula.com.br', 'rio-grande-da-serra', 'SP', null)
ON CONFLICT (slug) DO UPDATE SET category = EXCLUDED.category;
