-- Seed: Recreação (Recreadores, Personagens Vivos, Animação) - ABC Paulista
-- Cidades: Santo André, São Bernardo, São Caetano, Diadema, Mauá, Ribeirão Pires, Rio Grande da Serra

INSERT INTO public.providers (
  id, name, type, city_id, category_id, neighborhood, address, whatsapp, phone, email, source, active, created_at, slug, category, website, city_slug, state, creci
) VALUES
(gen_random_uuid(), 'Tio Melancia & Cia Recreação', null, (SELECT id FROM public.cities WHERE slug='santo-andre'), null, 'Paraíso', 'Atendimento Regional ABC', '11993847389', '11993847389', 'contato@tiomelancia.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'tio-melancia-recreacao-santo-andre', '', 'http://tiomelancia.com.br', 'santo-andre', 'SP', null),
(gen_random_uuid(), 'KING Entretenimentos', null, (SELECT id FROM public.cities WHERE slug='santo-andre'), null, 'Centro', 'Atendimento Santo André', '11917076784', '11917076784', 'comercial@entretenimentosking.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'king-entretenimentos-santo-andre', 'recreacao', 'http://entretenimentosking.com.br', 'santo-andre', 'SP', null),
(gen_random_uuid(), 'Quintal Corre Cotia', null, (SELECT id FROM public.cities WHERE slug='santo-andre'), null, 'Paraíso', 'R. Juazeiro, 52', '11964099152', '11964099152', null, 'manual_google', true, '2026-03-06T12:00:00', 'quintal-corre-cotia-santo-andre', 'recreacao', 'http://quintalcorrecotia.com.br', 'santo-andre', 'SP', null),
(gen_random_uuid(), 'Blitz Cosplay & Personagens', null, (SELECT id FROM public.cities WHERE slug='santo-andre'), null, 'Vila Bastos', 'Atendimento Regional', '11986683800', '11986683800', null, 'manual_google', true, '2026-03-06T12:00:00', 'blitz-cosplay-santo-andre', 'recreacao', 'http://blitzcosplay.com.br', 'santo-andre', 'SP', null),
(gen_random_uuid(), 'Fê e Fla Animação', null, (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), null, 'Centro', 'Atendimento SBC', '11988975909', '11988975909', null, 'manual_google', true, '2026-03-06T12:00:00', 'fe-e-fla-animacao-sbc', 'recreacao', null, 'sao-bernardo-do-campo', 'SP', null),
(gen_random_uuid(), 'Adventure Entretenimentos', null, (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), null, 'Rudge Ramos', 'Atendimento SBC', '11940414933', '1143631929', null, 'manual_google', true, '2026-03-06T12:00:00', 'adventure-entretenimentos-sbc', 'recreacao', 'http://www.adventureeventos.eev.com.br', 'sao-bernardo-do-campo', 'SP', null),
(gen_random_uuid(), 'Palhaço Tropeço', null, (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), null, 'Taboão', 'Atendimento SBC', '11950405009', '1141731176', null, 'manual_google', true, '2026-03-06T12:00:00', 'palhaco-tropeco-sbc', 'recreacao', 'http://www.palhacotropeco.eev.com.br', 'sao-bernardo-do-campo', 'SP', null),
(gen_random_uuid(), 'Fábulas & Contos Personagens', null, (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), null, 'Centro', 'Atendimento Regional', '11990043533', '11990043533', null, 'manual_google', true, '2026-03-06T12:00:00', 'fabulas-e-contos-sbc', 'recreacao', 'http://www.fabulasecontospersonagens.com.br', 'sao-bernardo-do-campo', 'SP', null),
(gen_random_uuid(), 'Espaço Sonho Dourado Recreação', null, (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), null, 'Santa Maria', 'Rua Ivaí, 426', '11942429242', '11942429242', null, 'manual_google', true, '2026-03-06T12:00:00', 'sonho-dourado-recreacao-scs', 'recreacao', 'http://espacosonhodourado.com.br', 'sao-caetano-do-sul', 'SP', null),
(gen_random_uuid(), 'Patuska Brincadeiras', null, (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), null, 'Barcelona', 'Atendimento São Caetano', '11995870203', '11995870203', 'contato@patuskabrincadeiras.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'patuska-brincadeiras-scs', 'recreacao', 'http://patuskabrincadeiras.com.br', 'sao-caetano-do-sul', 'SP', null),
(gen_random_uuid(), 'Além do Arco Íris Recreação', null, (SELECT id FROM public.cities WHERE slug='diadema'), null, 'Vila Nogueira', 'Rua Sebastião Fernandes Tourinho, 257', '11959024971', '11959024971', 'secretariaalemdoarcoiris@gmail.com', 'manual_google', true, '2026-03-06T12:00:00', 'alem-do-arco-iris-diadema', 'recreacao', 'http://alemdoarcoiris.com.br', 'diadema', 'SP', null),
(gen_random_uuid(), 'Hora de Brincar Recreação', null, (SELECT id FROM public.cities WHERE slug='diadema'), null, 'Jardim Takeby', 'Rua Yagamata, 163', '1140710597', '1140710597', 'soromaria@hotmail.com', 'manual_google', true, '2026-03-06T12:00:00', 'hora-de-brincar-diadema', 'recreacao', null, 'diadema', 'SP', null),
(gen_random_uuid(), 'Recanto da Arte (Animação)', null, (SELECT id FROM public.cities WHERE slug='santo-andre'), null, 'Centro', 'Atendimento Regional', '11987663741', '1132075767', null, 'manual_google', true, '2026-03-06T12:00:00', 'recanto-da-arte-animacao-abc', 'recreacao', 'http://recantodaarteshows.com.br', 'santo-andre', 'SP', null),
(gen_random_uuid(), 'UPALÊLÊ Brinquedos', null, (SELECT id FROM public.cities WHERE slug='maua'), null, 'Matriz', 'Atendimento Mauá', '11941481725', '11941481725', null, 'manual_google', true, '2026-03-06T12:00:00', 'upalele-brinquedos-maua', 'recreacao', 'http://upalelebrinquedosefestas.com.br', 'maua', 'SP', null),
(gen_random_uuid(), 'Tio Ivan Personagens', null, (SELECT id FROM public.cities WHERE slug='maua'), null, 'Jardim Sonia Maria', 'R. Zéquinha de Abreu, 620', '11988870117', '11988870117', null, 'manual_google', true, '2026-03-06T12:00:00', 'tio-ivan-personagens-maua', 'recreacao', null, 'maua', 'SP', null),
(gen_random_uuid(), 'Buffet Mundo Magia Recreação', null, (SELECT id FROM public.cities WHERE slug='ribeirao-pires'), null, 'Centro', 'Atendimento Ribeirão Pires', '11993847389', '11993847389', null, 'manual_google', true, '2026-03-06T12:00:00', 'mundo-magia-recreacao-ribeirao-pires', 'recreacao', 'http://buffetmundomagia.com.br', 'ribeirao-pires', 'SP', null),
(gen_random_uuid(), 'Batuta Brasil Entretenimento', null, (SELECT id FROM public.cities WHERE slug='ribeirao-pires'), null, 'Bocaina', 'Atendimento Regional', '11919848282', '11919848282', null, 'manual_google', true, '2026-03-06T12:00:00', 'batuta-brasil-ribeirao-pires', 'recreacao', 'http://batutabrasil.com.br', 'ribeirao-pires', 'SP', null),
(gen_random_uuid(), 'Malucolândia Recreação', null, (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), null, 'Centro', 'Atendimento Regional', '11959006935', '11959006935', 'contante@malucolandia.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'malucolandia-rgs', 'recreacao', 'http://malucolandia.com.br', 'rio-grande-da-serra', 'SP', null),
(gen_random_uuid(), 'Joie Festas Criativas', null, (SELECT id FROM public.cities WHERE slug='ribeirao-pires'), null, 'Centro', 'Atendimento Ribeirão', '11985368512', '11985368512', null, 'manual_google', true, '2026-03-06T12:00:00', 'joie-festas-ribeirao', 'recreacao', 'http://joiefestas.com.br', 'ribeirao-pires', 'SP', null),
(gen_random_uuid(), 'Alive Festas Personagens', null, (SELECT id FROM public.cities WHERE slug='santo-andre'), null, 'Jardim', 'Atendimento Regional ABC', '11964590602', '11964590602', null, 'manual_google', true, '2026-03-06T12:00:00', 'alive-festas-personagens-abc', 'recreacao', 'http://www.personagensvivosbrasil.com.br', 'santo-andre', 'SP', null)
ON CONFLICT (slug) DO UPDATE SET category = EXCLUDED.category;
