-- Seed: Locação de Carros por Assinatura - ABC Paulista
-- Cidades: Santo André, São Bernardo, São Caetano, Diadema, Mauá, Ribeirão Pires, Rio Grande da Serra

INSERT INTO public.providers (
  id, name, type, city_id, category_id, neighborhood, address, whatsapp, phone, email, source, active, created_at, slug, category, website, city_slug, state, creci
) VALUES
(gen_random_uuid(), 'Movida Carro por Assinatura - Santo André', null, (SELECT id FROM public.cities WHERE slug='santo-andre'), null, 'Centro', 'Rua Coronel Fernando Prestes, 680', '08007713010', '08007713010', null, 'manual_google', true, '2026-03-06T12:00:00', 'movida-assinatura-santo-andre', 'locacao_carros', 'https://www.movidazerokm.com.br', 'santo-andre', 'SP', null),
(gen_random_uuid(), 'Unidas Livre - Santo André', null, (SELECT id FROM public.cities WHERE slug='santo-andre'), null, 'Casa Branca', 'Av. Artur de Queiros, 685', '08007715158', '1151080079', null, 'manual_google', true, '2026-03-06T12:00:00', 'unidas-livre-santo-andre', 'locacao_carros', 'https://www.livre.com.br', 'santo-andre', 'SP', null),
(gen_random_uuid(), 'Localiza Meoo - Santo André Centro', null, (SELECT id FROM public.cities WHERE slug='santo-andre'), null, 'Centro', 'R. General Glicério, 749', '3130034774', '40001403', 'meoo.vendas@localiza.com', 'manual_google', true, '2026-03-06T12:00:00', 'localiza-meoo-santo-andre', 'locacao_carros', 'https://www.localiza.com/meoo', 'santo-andre', 'SP', null),
(gen_random_uuid(), 'Movida Carro por Assinatura - SBC Plaza', null, (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), null, 'Centro', 'Avenida Rotary, 624 (Shopping São Bernardo Plaza)', '08007713010', '08007713010', null, 'manual_google', true, '2026-03-06T12:00:00', 'movida-assinatura-sbc', 'locacao_carros', 'https://www.movidazerokm.com.br', 'sao-bernardo-do-campo', 'SP', null),
(gen_random_uuid(), 'Unidas Livre - SBC Plaza', null, (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), null, 'Centro', 'Av. Rotary, 624 (Shopping São Bernardo Plaza)', '08007715158', '08007715158', null, 'manual_google', true, '2026-03-06T12:00:00', 'unidas-livre-sbc', 'locacao_carros', 'https://www.livre.com.br', 'sao-bernardo-do-campo', 'SP', null),
(gen_random_uuid(), 'Hyundai Sinal Diadema - Assinatura', null, (SELECT id FROM public.cities WHERE slug='diadema'), null, 'Centro', 'Av. Fábio Eduardo Ramos Esquivel, 999', '11999999999', '1140532000', null, 'manual_google', true, '2026-03-06T12:00:00', 'hyundai-sinal-diadema', 'locacao_carros', 'https://www.gruposinal.com.br', 'diadema', 'SP', null),
(gen_random_uuid(), 'AssineDrive Diadema', null, (SELECT id FROM public.cities WHERE slug='diadema'), null, 'Centro', 'Atendimento Regional Diadema', '11999999999', '11999999999', 'contato@assinedrive.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'assine-drive-diadema', 'locacao_carros', 'https://www.assinedrive.com.br', 'diadema', 'SP', null),
(gen_random_uuid(), 'Ford Sinal São Caetano - Assinatura', null, (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), null, 'Centro', 'Rua Alagoas, 41', '11999999999', '1142234000', null, 'manual_google', true, '2026-03-06T12:00:00', 'ford-sinal-scs', 'locacao_carros', 'https://www.gruposinal.com.br', 'sao-caetano-do-sul', 'SP', null),
(gen_random_uuid(), 'Hyundai Sinal São Caetano - Assinatura', null, (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), null, 'Santo Antônio', 'Avenida Goiás, 3373', '11999999999', '1142237000', null, 'manual_google', true, '2026-03-06T12:00:00', 'hyundai-sinal-scs', 'locacao_carros', 'https://www.gruposinal.com.br', 'sao-caetano-do-sul', 'SP', null),
(gen_random_uuid(), 'Loca+ Veículos São Caetano', null, (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), null, 'Centro', 'Rua Amazonas, 1100', '11999999999', '1142235000', null, 'manual_google', true, '2026-03-06T12:00:00', 'loca-mais-scs', 'locacao_carros', 'https://www.locamaisveiculos.com.br', 'sao-caetano-do-sul', 'SP', null),
(gen_random_uuid(), 'AssineDrive Mauá', null, (SELECT id FROM public.cities WHERE slug='maua'), null, 'Centro', 'Atendimento Regional Mauá', '11999999999', '11999999999', 'contato@assinedrive.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'assine-drive-maua', 'locacao_carros', 'https://www.assinedrive.com.br', 'maua', 'SP', null),
(gen_random_uuid(), 'Panorama Veículos Locadora - Ribeirão Pires', null, (SELECT id FROM public.cities WHERE slug='ribeirao-pires'), null, 'Centro', 'Avenida Valdírio Prisco, 980', '11950421700', '1125951717', null, 'manual_google', true, '2026-03-06T12:00:00', 'panorama-locadora-ribeirao', 'locacao_carros', 'https://www.panoramaveiculos.com.br', 'ribeirao-pires', 'SP', null),
(gen_random_uuid(), 'KCG Locadora ABC - Rio Grande da Serra', null, (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), null, 'Centro', 'Atendimento Regional RGS', '11959995214', '11959995214', null, 'manual_google', true, '2026-03-06T12:00:00', 'kcg-locadora-rgs', 'locacao_carros', 'https://www.kcgsolar.com.br', 'rio-grande-da-serra', 'SP', null)
ON CONFLICT (slug) DO UPDATE SET 
  category = EXCLUDED.category,
  active = EXCLUDED.active;
