-- Seed: Paisagismo e Hortas - ABC Paulista
-- Cidades: Santo André, São Bernardo, São Caetano, Diadema, Mauá, Ribeirão Pires, Rio Grande da Serra

INSERT INTO public.providers (
  id, name, type, city_id, category_id, neighborhood, address, whatsapp, phone, email, source, active, created_at, slug, category, website, city_slug, state, creci
) VALUES
(gen_random_uuid(), 'Lótus Paisagismo e Irrigação', null, (SELECT id FROM public.cities WHERE slug='santo-andre'), null, 'Campestre', 'Rua Flora, 201', '11985660830', '11985660830', 'contato@lotuspaisagismo.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'lotus-paisagismo-santo-andre', 'paisagismo', 'http://lotuspaisagismo.com.br', 'santo-andre', 'SP', null),
(gen_random_uuid(), 'A Varanda Floricultura e Paisagismo', null, (SELECT id FROM public.cities WHERE slug='santo-andre'), null, 'Bela Vista', 'Praça Allan Kardec, 70 B', '1149903422', '1149903422', null, 'manual_google', true, '2026-03-06T12:00:00', 'a-varanda-paisagismo-santo-andre', 'paisagismo', 'http://www.avaranda.com.br', 'santo-andre', 'SP', null),
(gen_random_uuid(), 'ABC Garden São Bernardo', null, (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), null, 'Demarchi', 'Av. Maria Servidei Demarchi, 1850', '1143418299', '1143418299', 'contato@abcgarden.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'abc-garden-sbc', 'paisagismo', 'http://abcgarden.com.br', 'sao-bernardo-do-campo', 'SP', null),
(gen_random_uuid(), 'ABC Jardinagem Egrl', null, (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), null, 'Demarchi', 'Atendimento Regional SBC', '1143418299', '1143418299', null, 'manual_google', true, '2026-03-06T12:00:00', 'abc-jardinagem-sbc', 'paisagismo', null, 'sao-bernardo-do-campo', 'SP', null),
(gen_random_uuid(), 'Esquina do Verde', null, (SELECT id FROM public.cities WHERE slug='sao-caetano-do-sul'), null, 'Cerâmica', 'Av. Guido Aliberti, 2811', '1142312678', '1142312678', null, 'manual_google', true, '2026-03-06T12:00:00', 'esquina-do-verde-scs', 'paisagismo', 'http://esquinadoverde.com.br', 'sao-caetano-do-sul', 'SP', null),
(gen_random_uuid(), 'Floema Jardinagem e Paisagismo', null, (SELECT id FROM public.cities WHERE slug='diadema'), null, 'Centro', 'Avenida Sete de Setembro, 151', '1128053586', '1140572304', null, 'manual_google', true, '2026-03-06T12:00:00', 'floema-paisagismo-diadema', 'paisagismo', 'http://floemapaisagismo.com.br', 'diadema', 'SP', null),
(gen_random_uuid(), 'Garden Raiz Jardinagem', null, (SELECT id FROM public.cities WHERE slug='diadema'), null, 'Canhema', 'Rua Teófilo Braga, 45', '11944756035', '11944756035', null, 'manual_google', true, '2026-03-06T12:00:00', 'garden-raiz-diadema', 'paisagismo', null, 'diadema', 'SP', null),
(gen_random_uuid(), 'Malu Artes Jardinagem', null, (SELECT id FROM public.cities WHERE slug='maua'), null, 'Vila Noêmia', 'Atendimento Regional Mauá', '1145768820', '1145768820', null, 'manual_google', true, '2026-03-06T12:00:00', 'malu-artes-maua', 'paisagismo', null, 'maua', 'SP', null),
(gen_random_uuid(), 'Km Garden Pires', null, (SELECT id FROM public.cities WHERE slug='ribeirao-pires'), null, 'Ouro Fino', 'Rodovia Índio Tibiriçá, 4443', '1148285744', '1148285744', null, 'manual_google', true, '2026-03-06T12:00:00', 'km-garden-ribeirao', 'paisagismo', null, 'ribeirao-pires', 'SP', null),
(gen_random_uuid(), 'Verdy Paisagismo', null, (SELECT id FROM public.cities WHERE slug='ribeirao-pires'), null, 'Centro', 'Rodovia Índio Tibiriçá, 3005', '1149915000', '1149915000', 'comercial@verdypaisagismo.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'verdy-paisagismo-ribeirao', 'paisagismo', 'http://verdypaisagismo.com.br', 'ribeirao-pires', 'SP', null),
(gen_random_uuid(), 'Carol Flores Garden', null, (SELECT id FROM public.cities WHERE slug='rio-grande-da-serra'), null, 'Centro', 'Rua José Maria Figueiredo, 8', '1148211000', '1148211000', null, 'manual_google', true, '2026-03-06T12:00:00', 'carol-flores-rgs', 'paisagismo', null, 'rio-grande-da-serra', 'SP', null),
(gen_random_uuid(), 'Cityfarm Brasil - Hortas Urbanas', null, (SELECT id FROM public.cities WHERE slug='santo-andre'), null, 'Centro', 'Atendimento Regional ABC', '11999999999', '11999999999', 'contato@cityfarmbrasil.com.br', 'manual_google', true, '2026-03-06T12:00:00', 'cityfarm-brasil-abc', 'paisagismo', 'http://cityfarmbrasil.com.br', 'santo-andre', 'SP', null)
ON CONFLICT (slug) DO UPDATE SET 
  category = EXCLUDED.category,
  active = EXCLUDED.active;
