-- 97. Insert Pest Control (Dedetizadora) Providers (São Bernardo do Campo)

INSERT INTO public.providers (id, name, city_id, neighborhood, address, whatsapp, phone, email, source, active, slug, category, website, creci)
VALUES
  -- Encontrados com dados reais
  (gen_random_uuid(), 'EccoClean Dedetizadora', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'eccoclean-dedetizadora-sao-bernardo', 'dedetizadora', 'https://eccocleandedetizacao.com.br', null),
  (gen_random_uuid(), 'Dedetizadora 24 Horas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, '08007559000', null, 'manual_google', true, 'dedetizadora-24-horas-sao-bernardo', 'dedetizadora', 'https://dedetizadora.srv.br', null),
  (gen_random_uuid(), 'Protec Pragas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', '11940103334', null, null, 'manual_google', true, 'protec-pragas-sao-bernardo', 'dedetizadora', 'https://protecpragas.com.br', null),
  (gen_random_uuid(), 'Dedetizadora Angular', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, '11965110165', 'atendimento@dedetizadoraangular.com.br', 'manual_google', true, 'dedetizadora-angular-sao-bernardo', 'dedetizadora', 'https://dedetizadoraangular.com.br', null),
  (gen_random_uuid(), 'Lunar Dedetizadora', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'lunar-dedetizadora-sao-bernardo', 'dedetizadora', 'https://lunardedetizadora.com.br', null),
  (gen_random_uuid(), 'Dedetiza Bem', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'dedetiza-bem-sao-bernardo', 'dedetizadora', 'https://dedetizabem.com.br', null),
  (gen_random_uuid(), 'DTIZA Controle de Pragas', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'dtiza-controle-de-pragas-sao-bernardo', 'dedetizadora', 'https://dtiza.com.br', null),
  (gen_random_uuid(), 'Dedetizadora Lava Imper', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'dedetizadora-lava-imper-sao-bernardo', 'dedetizadora', 'https://dedetizadorbrasil.com.br', null),
  (gen_random_uuid(), 'Primos Dedetizadora', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'primos-dedetizadora-sao-bernardo', 'dedetizadora', 'https://primosdedetizadora.com.br', null),
  (gen_random_uuid(), 'Zet-Tec Dedetizadora', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'zet-tec-dedetizadora-sao-bernardo', 'dedetizadora', 'https://zet-tecdedetizadora.com.br', null),
  (gen_random_uuid(), 'Dedetizadora Menor Preço', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'dedetizadora-menor-preco-sao-bernardo', 'dedetizadora', 'https://dedetizadoramenorpreco.com.br', null),
  (gen_random_uuid(), 'Esgotécnica Dedetizadora', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'esgotecnica-dedetizadora-sao-bernardo', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Higitec Dedetizadora', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'higitec-dedetizadora-sao-bernardo', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Fast Serv Dedetizadora', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'fast-serv-dedetizadora-sao-bernardo', 'dedetizadora', null, null),
  (gen_random_uuid(), 'DD Drin Dedetizadora', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'dd-drin-dedetizadora-sao-bernardo', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Loremi Dedetizadora', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'loremi-dedetizadora-sao-bernardo', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Desentupidora e Dedetizadora Império', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'desentupidora-e-dedetizadora-imperio-sao-bernardo', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Osaka Dedetizadora', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'osaka-dedetizadora-sao-bernardo', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Dedetizadora Samurai', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'dedetizadora-samurai-sao-bernardo', 'dedetizadora', null, null),
  (gen_random_uuid(), 'Dedetizadora e Desentupidora Econômica', (SELECT id FROM public.cities WHERE slug='sao-bernardo-do-campo'), 'Centro', 'São Bernardo do Campo - SP', null, null, null, 'manual_google', true, 'dedetizadora-e-desentupidora-economica-sao-bernardo', 'dedetizadora', null, null)
ON CONFLICT (slug) DO NOTHING;
